 <?php
 // module/Video/view/video/video/index.phtml:
 $title = $this->translate('videopagetitle');
 $this->headTitle($title);
 ?>
            <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <?php echo $this->escapeHtml($title); ?>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
                        <li class="active"><?php echo $this->translate('videopagetitle');?></li>
                    </ol>
                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <div id="error" style="display: none" class="callout callout-danger">
                                        
                                    </div>
                                    <p>
                                        <a href="<?php echo $this->url('Video', array('action'=>'add'));?>"><?php echo $this->translate('add');?></a>
                                    </p>
                                </div>
                                <div class="box-body">
                                    <table id="videoDataTable" class="table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th><?php echo $this->translate('tableid');?></th>
                                                <th><?php echo $this->translate('tabletitle');?></th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    
                </section><!-- /.content -->
 
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
    var datatable;
        function fulldata(){
            $('#videoDataTable').DataTable( {
                "processing": true,
                "serverSide": true,
                "ajax": "<?php echo $this->url('Video', array('action'=>'getAllPages'));?>"
            } );
        };
        
        fulldata();
         
        
        
     });

     <?php $this->inlineScript()->captureEnd() ?>


 