 <?php
 $title = $this->translate('programspagetitle');
 $this->headTitle($title);
 ?>
            <!-- Content Header (Program header) -->
                <section class="content-header">
                    <h1>
                        <?php echo $this->escapeHtml($title); ?>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
                        <li class="active"><?php echo $this->escapeHtml($title); ?></li>
                    </ol>
                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <div id="error" style="display: none" class="callout callout-danger">
                                        
                                    </div>
                                    <p>
                                        <a href="<?php echo $this->url('Programs', array('action'=>'add'));?>"><?php echo $this->translate('add');?></a>
                                    </p>
                                </div>
                                <div class="box-body">
                                    <p><?php echo $this->translate('todaypagetitle');?></p>
                                    <table id="albumDataTable" class="table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                            	<th><?php echo $this->translate('order');?> </th>
                                                <th><?php echo $this->translate('tableid');?></th>
                                                <th><?php echo $this->translate('name');?> <?php echo $this->translate('arabic');?> </th>
                                                <th><?php echo $this->translate('name');?> <?php echo $this->translate('english');?> </th>
                                                <th><?php echo $this->translate('tableoptions');?></th>
                                            </tr>
                                        </thead>
                                    </table>
                                    <p><?php echo $this->translate('tomorrowpagetitle');?></p>
                                    <table id="nextDataTable" class="table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                            	<th><?php echo $this->translate('order');?> </th>
                                                <th><?php echo $this->translate('tableid');?></th>
                                                <th><?php echo $this->translate('name');?> <?php echo $this->translate('arabic');?> </th>
                                                <th><?php echo $this->translate('name');?> <?php echo $this->translate('english');?> </th>
                                                <th><?php echo $this->translate('tableoptions');?></th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </section><!-- /.content -->
                
                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    
                </div>
                <!-- /.modal -->


<?php $this->headScript()->appendFile('plugins/datatables/js/jquery.dataTables.rowReordering.js') ?>
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
    var datatable;
    var datatable1;
        function fulldata(){
        
            datatable = $('#albumDataTable').DataTable({
            "destroy": true,
            "searching": true,
            "processing": true,
             "order" : [[3,"desc"]],
            "ajax" : "<?php echo $this->url('Programs', array('action'=>'getAll','id'=>'1'));?>",
            "createdRow" : function( row, data, index ) {
			        if( data.hasOwnProperty("id") ) {
			            row.id = data.id;
			        }       
			    },
            "columnDefs" : [{
			    "targets": 0,
			    "visible": false,
                            "data": "ord",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 1,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 2,
                            "data": "name",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 3,
                            "data": "enname",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 4,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
                                    var activeicon='fa fa-close';
                                    var activemsg='Activate';
                                    if(full.active){
                                    activeicon='fa fa-check';
                                    activemsg='Deactivate';
                                    }
                                    
                                    return "<a rel='" + data + "' class='btn btn-xs chstatus' data-toggle='tooltip' data-placement='top' title='"+ activemsg +"'><i class='"+ activeicon +"'></i></a>\n\
                                            <a href='<?php echo $this->url('Programs', array('action'=>'edit'));?>/"+ data +"' class='btn btn-xs' data-toggle='tooltip' data-placement='top' title='Edit'><i class='fa fa-edit'></i></a>\n\
                                            <a rel='"+ data +"' class='btn btn-xs delete' data-toggle='tooltip' data-placement='top' title='Delete'><i class='fa fa-trash'></i></a>";
                                }
                        }]
            }).rowReordering({ 
                              sURL:"<?php echo $this->url('Programs', array('action'=>'order'));?>",
                              sRequestType: "POST",
                              fnAlert: function(message) { 
                                              alert(message);
                                       }
                               });
           datatable1 = $('#nextDataTable').DataTable({
            "destroy": true,
            "searching": true,
            "processing": true,
             "order" : [[3,"desc"]],
            "ajax" : "<?php echo $this->url('Programs', array('action'=>'getAll','id'=>'2'));?>",
            "createdRow" : function( row, data, index ) {
			        if( data.hasOwnProperty("id") ) {
			            row.id = data.id;
			        }       
			    },
            "columnDefs" : [{
			    "targets": 0,
			    "visible": false,
                            "data": "ord",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 1,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 2,
                            "data": "name",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 3,
                            "data": "enname",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 4,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
                                    var activeicon='fa fa-close';
                                    var activemsg='Activate';
                                    if(full.active){
                                    activeicon='fa fa-check';
                                    activemsg='Deactivate';
                                    }
                                    
                                    return "<a rel='" + data + "' class='btn btn-xs chstatus' data-toggle='tooltip' data-placement='top' title='"+ activemsg +"'><i class='"+ activeicon +"'></i></a>\n\
                                            <a href='<?php echo $this->url('Programs', array('action'=>'edit'));?>/"+ data +"' class='btn btn-xs' data-toggle='tooltip' data-placement='top' title='Edit'><i class='fa fa-edit'></i></a>\n\
                                            <a rel='"+ data +"' class='btn btn-xs delete' data-toggle='tooltip' data-placement='top' title='Delete'><i class='fa fa-trash'></i></a>";
                                }
                        }]
            }).rowReordering({ 
                              sURL:"<?php echo $this->url('Programs', array('action'=>'order'));?>",
                              sRequestType: "POST",
                              fnAlert: function(message) { 
                                              alert(message);
                                       }
                               });
        };
        
        fulldata();
         
        $('#albumDataTable tbody').on('click', '.delete', function () {
            var data = $(this).attr('rel');
            var el = this;
            bootbox.confirm("<?php echo $this->translate('yesorno');?>", function(result) {
                if(result){
                    $.post(
                            "<?php echo $this->url('Programs', array('action'=>'delete'));?>/"+data,
                             function (data){
                                 //data = JSON.stringify(data);
                                 if(data.done == 'true'){
                                     //fulldata();
                                     datatable.row( $(el).parents('tr') )
					        .remove()
					        .draw(false);
                                 }else{
                                 $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                                     $('#error').show(150);
                                 }
                             }
                    );
                }
            });
        });
        $('#nextDataTable tbody').on('click', '.delete', function () {
            var data = $(this).attr('rel');
            var el = this;
            bootbox.confirm("<?php echo $this->translate('yesorno');?>", function(result) {
                if(result){
                    $.post(
                            "<?php echo $this->url('Programs', array('action'=>'delete'));?>/"+data,
                             function (data){
                                 //data = JSON.stringify(data);
                                 if(data.done == 'true'){
                                     //fulldata();
                                     datatable1.row( $(el).parents('tr') )
					        .remove()
					        .draw(false);
                                 }else{
                                 $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                                     $('#error').show(150);
                                 }
                             }
                    );
                }
            });
        });
        $('#albumDataTable tbody').on('click', '.chstatus', function () {
            var data = $(this).attr('rel');
            var el = this;
            $.post(
                    "<?php echo $this->url('Programs', array('action'=>'chstatus'));?>/"+data,
                     function (data){
                         if(data.done == 'true'){
                             //fulldata();
                             if( $(el).attr('title') == "Activate"){
                             	$(el).attr('title', "Deactivate");
                             	$(el).find(".fa.fa-close").attr('class','fa fa-check');
                             }else{
                             	$(el).attr('title', "Activate");
                             	$(el).find(".fa.fa-check").attr('class','fa fa-close');
                             }
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
        
        $('#nextDataTable tbody').on('click', '.chstatus', function () {
            var data = $(this).attr('rel');
             var el = this;
            $.post(
                    "<?php echo $this->url('Programs', array('action'=>'chstatus'));?>/"+data,
                     function (data){
                         if(data.done == 'true'){
                             //fulldata();
                             if( $(el).attr('title') == "Activate"){
                             	$(el).attr('title', "Deactivate");
                             	$(el).find(".fa.fa-close").attr('class','fa fa-check');
                             }else{
                             	$(el).attr('title', "Activate");
                             	$(el).find(".fa.fa-check").attr('class','fa fa-close');
                             }
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
        
        $('#albumDataTable tbody').on('click', '.permissions', function () {
            var url = $(this).attr('rel');
            //alert(url);
            $('#myModal').load(url);
            $('#myModal').modal('show');
        });
        $('#nextDataTable tbody').on('click', '.permissions', function () {
            var url = $(this).attr('rel');
            //alert(url);
            $('#myModal').load(url);
            $('#myModal').modal('show');
        });
        
        
        
     });

     <?php $this->inlineScript()->captureEnd() ?>


 