<?php $this->layout('layout/login'); ?>
<div class="login-box-body">
    <p class="login-box-msg"><?php echo $this->translate('Sign In'); ?></p>
    <?php
    $form = $this->loginForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/login'));
    $form->setAttribute('method', 'post');
    ?>

    <?php echo $this->form()->openTag($form) ?>

    <?php echo $this->formElementErrors($form->get('identity')) ?>

        <!-- <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt> -->

        <div class="form-group has-feedback">
            <?php echo $this->formInput($form->get('identity')->setAttribute('placeholder','Email')->setAttribute('class','form-control')) ?>

            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
            <?php echo $this->formInput($form->get('credential')->setAttribute('placeholder','Password')->setAttribute('class','form-control')) ?>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
        <div class="row">
            <div class="col-xs-8">    
                <div class="checkbox icheck">
                    <label>
                        <input type="checkbox"> Remember Me
                    </label>
                </div>                        
            </div><!-- /.col -->
            <div class="col-xs-4">
                <?php echo $this->formButton($form->get('submit')->setAttribute('class','btn btn-primary btn-block btn-flat')) ?>
            </div><!-- /.col -->
        </div>

    <?php echo $this->form()->closeTag() ?>
    <?php if ($this->enableRegistration) : ?>
        <?php echo $this->translate('Not registered?'); ?> <!-- <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a> -->
         <a href="http://alaqila.tv/signup/"><?php echo $this->translate('Sign up!'); ?></a> 
    <?php endif; ?>

</div><!-- /.login-box-body -->
<?php $this->inlineScript()->captureStart() ?>
$(function () {
    $('input').iCheck({
        checkboxClass: 'icheckbox_square-blue',
        radioClass: 'iradio_square-blue',
        increaseArea: '20%' // optional
    });
});
<?php $this->inlineScript()->captureEnd() ?>
