<?php
// module/Album/view/album/album/edit.phtml:

$title = $this->translate('edit')." ".$this->translate('userspagetitle');
$this->headTitle($title);
?>

<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($title); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
        <li><a href="<?php echo $this->url('Users') ?>"><?php echo $this->translate('userspagetitle');?></a></li>
        <li class="active"><?php echo $this->escapeHtml($title); ?></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <!-- general form elements disabled -->
            <div class="box box-primary">

                <div class="box-body">

                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('Users', array('action' => 'edit', 'id' => $this->id,)));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('facebook'));
                    echo $this->formHidden($form->get('instagram'));
                    echo $this->formHidden($form->get('twitter'));
                    echo $this->formHidden($form->get('livestream'));
                    ?>
                    <div class="form-group">
                        <label for='username'><?php echo $this->translate('usernameform');?></label>
                        <?php
                        echo $this->formRow($form->get('username'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='displayName'><?php echo $this->translate('displaynameform');?></label>
                        <?php
                        echo $this->formRow($form->get('displayName'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='photo'><?php echo $this->translate('imageform');?></label>
                        <?php
                        echo $this->formRow($form->get('photo'));
                        ?>
                        <a rel='<?php echo $this->url('Myuploads') ?>' for="photo" class='btn btn-xs mida' data-toggle='modal' title='Users Roles'><i class='fa fa-picture-o'></i></a>
                    </div>

                    <div class="form-group">
                        <label for='email'><?php echo $this->translate('emailform');?></label>
                        <?php
                        echo $this->formRow($form->get('email'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='password'><?php echo $this->translate('passwordform');?></label>
                        <?php
                        echo $this->formRow($form->get('password'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='passwordconfirm'><?php echo $this->translate('passwordconfirmform');?></label>
                        <?php
                        echo $this->formRow($form->get('passwordconfirm'));
                        ?>
                    </div>

                    <div class="box-footer">
                        <?php
                        echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Modal -->
    <input type="hidden" name="parentName" id="parentName" value=""/> 
    <div class="modal fade" id="MediaLibraryModal" tabindex="-1" role="dialog" aria-labelledby="MediaLibraryModalLabel" aria-hidden="true">
                   
    </div>

</section
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
        $('.mida').on('click', function () {
            var url = $(this).attr('rel');
            var parent = $(this).attr('for');
            $('#MediaLibraryModal').load(url);
            $('#MediaLibraryModal').modal('show');
            $("#parentName").val(parent);
        });
    });
<?php $this->inlineScript()->captureEnd() ?>
