 <?php
 $title = $this->translate('userspagetitle');
 $this->headTitle($title);
 ?>
            <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <?php echo $this->escapeHtml($title); ?>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
                        <li class="active"><?php echo $this->translate('userspagetitle');?></li>
                    </ol>
                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <div id="error" style="display: none" class="callout callout-danger"></div>
                                    <p>
                                        <a href="<?php echo $this->url('Users', array('action'=>'add'));?>"><?php echo $this->translate('add');?></a>
                                    </p>
                                </div>
                                
                                <div class="box-body">
                                    <table id="userDataTable" class="table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th><?php echo $this->translate('tableid');?></th>
                                                <th><?php echo $this->translate('tableusername');?></th>
                                                <th><?php echo $this->translate('tableemail');?></th>
                                                <th><?php echo $this->translate('tabledisplayname');?></th>
                                                <th><?php echo $this->translate('tablestatus');?></th>
                                                <th><?php echo $this->translate('tableispublic');?></th>
                                                <th><?php echo $this->translate('tableisadmin');?></th>
                                                <th><?php echo $this->translate('tableissupervisor');?></th>
                                                <th><?php echo $this->translate('tableoptions');?></th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    
                </section><!-- /.content -->
 
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
        function fulldata(){
            $('#userDataTable').dataTable({
            "destroy": true,
            "lengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]],
            "searching": true,
            "ordering": true,
            "processing": true,
            "ajax" : "<?php echo $this->url('Users', array('action'=>'getAll'));?>",
            "columnDefs" : [{
                            "targets": 0,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 1,
                            "data": "username",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 2,
                            "data": "email",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 3,
                            "data": "displayName",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 4,
                            "data": "state",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 5,
                            "data": "isPublic",
                            <?php if($this->zfcUserIdentity()->getIsAdmin()!='1') echo '"visible": false,';?>
                            "render": function ( data, type, full, meta ) {
                                        var ispublicicon='fa fa-close';
                                        var ispublicmsg='Set As Public';
                                        if(data==1){
                                            ispublicicon='fa fa-check';
                                            ispublicmsg='Set As Private';
                                        }
                                        return "<a rel='" + full.id + "' class='btn btn-xs chpublic' data-toggle='tooltip' data-placement='top' title='"+ ispublicmsg +"'><i class='"+ ispublicicon +"'></i></a>";
                                    }
				},{
			    "targets": 6,
                            "data": "isAdmin",
                            <?php if($this->zfcUserIdentity()->getIsAdmin()!='1') echo '"visible": false,';?>
                            "render": function ( data, type, full, meta ) {
                                        var isadminicon='fa fa-close';
                                        var isadminmsg='Set As Admin';
                                        if(data==1){
                                            isadminicon='fa fa-check';
                                            isadminmsg='Set As User';
                                        }
                                        return "<a rel='" + full.id + "' class='btn btn-xs chtype' data-toggle='tooltip' data-placement='top' title='"+ isadminmsg +"'><i class='"+ isadminicon +"'></i></a>";
                                    }
				},{
                            "targets": 7,
                            "data": "isAdmin",
                            <?php if($this->zfcUserIdentity()->getIsAdmin()!='1') echo '"visible": false,';?>
                            "render": function ( data, type, full, meta ) {
                                        var isadminicon='fa fa-close';
                                        var isadminmsg='Set As Supervisor';
                                        if(data==2){
                                            isadminicon='fa fa-check';
                                            isadminmsg='Set As User';
                                        }
                                        return "<a rel='" + full.id + "' class='btn btn-xs chtypesv' data-toggle='tooltip' data-placement='top' title='"+ isadminmsg +"'><i class='"+ isadminicon +"'></i></a>";
                                    }
				},{
                            "targets": 8,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
                                    return "<a href='<?php echo $this->url('Users', array('action'=>'edit'));?>/"+ data +"' class='btn btn-xs' data-toggle='tooltip' data-placement='top' title='Edit'><i class='fa fa-edit'></i></a>\n\
                                <a href='<?php echo $this->url('Users', array('action'=>'settings'));?>/"+ data +"' class='btn btn-xs' data-toggle='tooltip' data-placement='top' title='Settings'><i class='fa fa-cog'></i></a>\n\
                                <a rel='"+ data +"' class='btn btn-xs delete' data-toggle='tooltip' data-placement='top' title='Delete'><i class='fa fa-trash'></i></a>";
                                }
                        }]
            });
        };
        
        fulldata();
         
        $('#userDataTable tbody').on('click', '.delete', function () {
            var data = $(this).attr('rel');
            bootbox.confirm("<?php echo $this->translate('yesorno');?>", function(result) {
                if(result){
                    $.post(
                            "<?php echo $this->url('Users', array('action'=>'delete'));?>/"+data,
                             function (data){
                                 if(data.done == 'true'){
                                     fulldata();
                                 }else{
                                 $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                                     $('#error').show(150);
                                 }
                             }
                    );
                }
            }); 
        });
        
        $('#userDataTable tbody').on('click', '.chtype', function () {
            var data = $(this).attr('rel');
            var el = this;
            $.post(
                    "<?php echo $this->url('Users', array('action'=>'chtype'));?>/"+data,
                     function (data){
                         if(data.done == 'true'){
                             //fulldata();
                             if( $(el).attr('title') == "Set As Admin"){
                             	$(el).attr('title', "Set As User");
                             	$(el).find(".fa.fa-close").attr('class','fa fa-check');
                             }else{
                             	$(el).attr('title', "Set As Admin");
                             	$(el).find(".fa.fa-check").attr('class','fa fa-close');
                             }
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
        $('#userDataTable tbody').on('click', '.chpublic', function () {
            var data = $(this).attr('rel');
            var el = this;
            $.post(
                    "<?php echo $this->url('Users', array('action'=>'chpublic'));?>/"+data,
                     function (data){
                         if(data.done == 'true'){
                             //fulldata();
                             if( $(el).attr('title') == "Set As Public"){
                             	$(el).attr('title', "Set As Private");
                             	$(el).find(".fa.fa-close").attr('class','fa fa-check');
                             }else{
                             	$(el).attr('title', "Set As Public");
                             	$(el).find(".fa.fa-check").attr('class','fa fa-close');
                             }
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
        $('#userDataTable tbody').on('click', '.chtypesv', function () {
            var data = $(this).attr('rel');
            var el = this;
            $.post(
                    "<?php echo $this->url('Users', array('action'=>'chtypesv'));?>/"+data,
                     function (data){
                         if(data.done == 'true'){
                             //fulldata();
                             if( $(el).attr('title') == "Set As Supervisor"){
                             	$(el).attr('title', "Set As User");
                             	$(el).find(".fa.fa-close").attr('class','fa fa-check');
                             }else{
                             	$(el).attr('title', "Set As Supervisor");
                             	$(el).find(".fa.fa-check").attr('class','fa fa-close');
                             }
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
     });
     
     

     <?php $this->inlineScript()->captureEnd() ?>


 
