<?php
// module/Album/view/album/album/edit.phtml:

$title = $this->translate('edit')." ".$this->translate('settings')." ".$this->translate('userspagetitle');
$this->headTitle($title);
?>

<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($title); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
        <li><a href="<?php echo $this->url('Users') ?>"><?php echo $this->translate('userspagetitle');?></a></li>
        <li class="active"><?php echo $this->escapeHtml($title); ?></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <!-- general form elements disabled -->
            <div class="box box-primary">

                <div class="box-body">

                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('Users', array('action' => 'settings', 'id' => $this->id,)));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('username'));
                    echo $this->formHidden($form->get('displayName'));
                    echo $this->formHidden($form->get('photo'));
                    echo $this->formHidden($form->get('email'));
                    echo $this->formHidden($form->get('password'));
                    ?>
                    <div class="form-group">
                        <label for='facebook'>Facebook <?php echo $this->translate('urlform');?></label>
                        <?php
                        echo $this->formRow($form->get('facebook'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='instagram'>Instagram <?php echo $this->translate('urlform');?></label>
                        <?php
                        echo $this->formRow($form->get('instagram'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='twitter'>Twitter <?php echo $this->translate('urlform');?></label>
                        <?php
                        echo $this->formRow($form->get('twitter'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='livestream'>Live Stream <?php echo $this->translate('urlform');?></label>
                        <?php
                        echo $this->formRow($form->get('livestream'));
                        ?>
                    </div>

                    <div class="box-footer">
                        <?php
                        echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>