<?php
// module/Album/view/album/album/add.phtml:
$title = $this->translate('add')." ".$this->translate('pagespagetitle');
$this->headTitle($title);
?>
<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($title); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a onclick="selecteOneIcon(this)" href="#<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
        <li><a onclick="selecteOneIcon(this)" href="#<?php echo $this->url('Pages') ?>"><?php echo $this->translate('pagespagetitle');?></a></li>
        <li class="active"><?php echo $this->escapeHtml($title); ?></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <!-- general form elements disabled -->
            <div class="box box-primary">

                <div class="box-body">

                    <?php
                    $form->setAttribute('action', $this->url('Pages', array('action' => 'add')));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('ord'));
                    ?>
                    <div class="form-group">
                        <label for='name'><?php echo $this->translate('name');?> <?php echo $this->translate('arabic');?></label>
                        <?php
                        echo $this->formRow($form->get('name'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='enname'><?php echo $this->translate('name');?> <?php echo $this->translate('english');?></label>
                        <?php
                        echo $this->formRow($form->get('enname'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='image'><?php echo $this->translate('imageform');?></label>
                        <?php
                        echo $this->formRow($form->get('image'));
                        ?>
                        <a rel='<?php echo $this->url('Myuploads') ?>' for="photo" class='btn btn-xs mida' data-toggle='modal' title='Users Roles'><i class='fa fa-picture-o'></i></a>
                    </div>

                    <div class="box-footer">
                        <?php
                        echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</section>
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
        $('.mida').on('click', function () {
            //var url = $(this).attr('rel');
            var parent = $(this).attr('for');
            //$('#MediaLibraryModal').load(url);
            $('#MediaLibraryModal').modal('show');
            $("#parentName").val(parent);
        });
    });
<?php $this->inlineScript()->captureEnd() ?>

    
    <script type="text/javascript" >
        var selectedIcon = ""; 
        function selecteOneIcon(selected){
            selectedIcon = selected.getElementsByTagName("i")[0].className.split(' ');
            //alert();
            //$('#selecteLable').html(selectedFile);
            //$('.thumbnail').removeClass('selected');
            $('#'+$('#parentName').val()).val(selectedIcon[1]);
            $("#MediaLibraryModal").modal("hide");
        }
              
    </script>
    
    <!-- Modal -->
    <input type="hidden" name="parentName" id="parentName" value=""/> 
    <div class="modal fade" id="MediaLibraryModal" tabindex="-1" role="dialog" aria-labelledby="MediaLibraryModalLabel" aria-hidden="true">
         <div class="modal-dialog uplodeModal">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Icons</h4>
                </div>
                <div class="modal-body">
                    <div class="row" style="max-height: 400px;overflow: auto;">
                        <div class="col-md-12">
                                
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="glass|martini|drink|bar|alcohol|liquor">
      <a onclick="selecteOneIcon(this)" href="##glass"><i class="fa fa-glass"></i> glass</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="music|note|sound">
        <a onclick="selecteOneIcon(this)" href="#music"><i class="fa fa-music"></i> music</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="search|magnify|zoom|enlarge|bigger">
      <a onclick="selecteOneIcon(this)" href="##search"><i class="fa fa-search"></i> search</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="envelope-o|email|support|e-mail|letter|mail|notification">
      <a onclick="selecteOneIcon(this)" href="##envelope-o"><i class="fa fa-envelope-o"></i> envelope-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="heart|love|like|favorite">
      <a onclick="selecteOneIcon(this)" href="##heart"><i class="fa fa-heart"></i> heart</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="star|award|achievement|night|rating|score">
      <a onclick="selecteOneIcon(this)" href="##star"><i class="fa fa-star"></i> star</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="star-o|award|achievement|night|rating|score">
      <a onclick="selecteOneIcon(this)" href="##star-o"><i class="fa fa-star-o"></i> star-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="user|person|man|head|profile">
      <a onclick="selecteOneIcon(this)" href="##user"><i class="fa fa-user"></i> user</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="film|movie">
      <a onclick="selecteOneIcon(this)" href="##film"><i class="fa fa-film"></i> film</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="th-large|blocks|squares|boxes">
      <a onclick="selecteOneIcon(this)" href="##th-large"><i class="fa fa-th-large"></i> th-large</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="th|blocks|squares|boxes">
      <a onclick="selecteOneIcon(this)" href="##th"><i class="fa fa-th"></i> th</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="th-list|ul|ol|checklist|finished|completed|done|todo">
      <a onclick="selecteOneIcon(this)" href="##th-list"><i class="fa fa-th-list"></i> th-list</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="check|checkmark|done|todo|agree|accept|confirm">
      <a onclick="selecteOneIcon(this)" href="##check"><i class="fa fa-check"></i> check</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="times|remove|close|close|exit|x">
      <a onclick="selecteOneIcon(this)" href="##times"><i class="fa fa-times"></i> times</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="search-plus|magnify|zoom|enlarge|bigger">
      <a onclick="selecteOneIcon(this)" href="##search-plus"><i class="fa fa-search-plus"></i> search-plus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="search-minus|magnify|minify|zoom|smaller">
      <a onclick="selecteOneIcon(this)" href="##search-minus"><i class="fa fa-search-minus"></i> search-minus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="power-off|on">
      <a onclick="selecteOneIcon(this)" href="##power-off"><i class="fa fa-power-off"></i> power-off</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="signal">
      <a onclick="selecteOneIcon(this)" href="##signal"><i class="fa fa-signal"></i> signal</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cog|gear|settings">
      <a onclick="selecteOneIcon(this)" href="##cog"><i class="fa fa-cog"></i> cog</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="trash-o|garbage|delete|remove|trash|hide">
      <a onclick="selecteOneIcon(this)" href="##trash-o"><i class="fa fa-trash-o"></i> trash-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="home|main|house">
      <a onclick="selecteOneIcon(this)" href="##home"><i class="fa fa-home"></i> home</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-o|new|page|pdf|document">
      <a onclick="selecteOneIcon(this)" href="##file-o"><i class="fa fa-file-o"></i> file-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="clock-o|watch|timer|late|timestamp">
      <a onclick="selecteOneIcon(this)" href="##clock-o"><i class="fa fa-clock-o"></i> clock-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="road|street">
      <a onclick="selecteOneIcon(this)" href="##road"><i class="fa fa-road"></i> road</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="download|import">
      <a onclick="selecteOneIcon(this)" href="##download"><i class="fa fa-download"></i> download</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-circle-o-down|download">
      <a onclick="selecteOneIcon(this)" href="##arrow-circle-o-down"><i class="fa fa-arrow-circle-o-down"></i> arrow-circle-o-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-circle-o-up">
      <a onclick="selecteOneIcon(this)" href="##arrow-circle-o-up"><i class="fa fa-arrow-circle-o-up"></i> arrow-circle-o-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="inbox">
      <a onclick="selecteOneIcon(this)" href="##inbox"><i class="fa fa-inbox"></i> inbox</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="play-circle-o">
      <a onclick="selecteOneIcon(this)" href="##play-circle-o"><i class="fa fa-play-circle-o"></i> play-circle-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="repeat|rotate-right|redo|forward">
      <a onclick="selecteOneIcon(this)" href="##repeat"><i class="fa fa-repeat"></i> repeat</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="refresh|reload">
      <a onclick="selecteOneIcon(this)" href="##refresh"><i class="fa fa-refresh"></i> refresh</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="list-alt|ul|ol|checklist|finished|completed|done|todo">
      <a onclick="selecteOneIcon(this)" href="##list-alt"><i class="fa fa-list-alt"></i> list-alt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="lock|protect|admin">
      <a onclick="selecteOneIcon(this)" href="##lock"><i class="fa fa-lock"></i> lock</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="flag|report|notification|notify">
      <a onclick="selecteOneIcon(this)" href="##flag"><i class="fa fa-flag"></i> flag</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="headphones|sound|listen|music">
      <a onclick="selecteOneIcon(this)" href="##headphones"><i class="fa fa-headphones"></i> headphones</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="volume-off|mute|sound|music">
      <a onclick="selecteOneIcon(this)" href="##volume-off"><i class="fa fa-volume-off"></i> volume-off</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="volume-down|lower|quieter|sound|music">
      <a onclick="selecteOneIcon(this)" href="##volume-down"><i class="fa fa-volume-down"></i> volume-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="volume-up|higher|louder|sound|music">
      <a onclick="selecteOneIcon(this)" href="##volume-up"><i class="fa fa-volume-up"></i> volume-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="qrcode|scan">
      <a onclick="selecteOneIcon(this)" href="##qrcode"><i class="fa fa-qrcode"></i> qrcode</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="barcode|scan">
      <a onclick="selecteOneIcon(this)" href="##barcode"><i class="fa fa-barcode"></i> barcode</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tag|label">
      <a onclick="selecteOneIcon(this)" href="##tag"><i class="fa fa-tag"></i> tag</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tags|labels">
      <a onclick="selecteOneIcon(this)" href="##tags"><i class="fa fa-tags"></i> tags</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="book|read|documentation">
      <a onclick="selecteOneIcon(this)" href="##book"><i class="fa fa-book"></i> book</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bookmark|save">
      <a onclick="selecteOneIcon(this)" href="##bookmark"><i class="fa fa-bookmark"></i> bookmark</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="print">
      <a onclick="selecteOneIcon(this)" href="##print"><i class="fa fa-print"></i> print</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="camera|photo|picture|record">
      <a onclick="selecteOneIcon(this)" href="##camera"><i class="fa fa-camera"></i> camera</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="font|text">
      <a onclick="selecteOneIcon(this)" href="##font"><i class="fa fa-font"></i> font</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bold">
      <a onclick="selecteOneIcon(this)" href="##bold"><i class="fa fa-bold"></i> bold</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="italic|italics">
      <a onclick="selecteOneIcon(this)" href="##italic"><i class="fa fa-italic"></i> italic</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="text-height">
      <a onclick="selecteOneIcon(this)" href="##text-height"><i class="fa fa-text-height"></i> text-height</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="text-width">
      <a onclick="selecteOneIcon(this)" href="##text-width"><i class="fa fa-text-width"></i> text-width</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="align-left|text">
      <a onclick="selecteOneIcon(this)" href="##align-left"><i class="fa fa-align-left"></i> align-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="align-center|middle|text">
      <a onclick="selecteOneIcon(this)" href="##align-center"><i class="fa fa-align-center"></i> align-center</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="align-right|text">
      <a onclick="selecteOneIcon(this)" href="##align-right"><i class="fa fa-align-right"></i> align-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="align-justify|text">
      <a onclick="selecteOneIcon(this)" href="##align-justify"><i class="fa fa-align-justify"></i> align-justify</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="list|ul|ol|checklist|finished|completed|done|todo">
      <a onclick="selecteOneIcon(this)" href="##list"><i class="fa fa-list"></i> list</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="outdent|dedent">
      <a onclick="selecteOneIcon(this)" href="##outdent"><i class="fa fa-outdent"></i> outdent</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="indent">
      <a onclick="selecteOneIcon(this)" href="##indent"><i class="fa fa-indent"></i> indent</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="video-camera|film|movie|record">
      <a onclick="selecteOneIcon(this)" href="##video-camera"><i class="fa fa-video-camera"></i> video-camera</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="picture-o|photo|image">
      <a onclick="selecteOneIcon(this)" href="##picture-o"><i class="fa fa-picture-o"></i> picture-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pencil|write|edit|update">
      <a onclick="selecteOneIcon(this)" href="##pencil"><i class="fa fa-pencil"></i> pencil</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="map-marker|map|pin|location|coordinates|localize|address|travel|where|place">
      <a onclick="selecteOneIcon(this)" href="##map-marker"><i class="fa fa-map-marker"></i> map-marker</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="adjust|contrast">
      <a onclick="selecteOneIcon(this)" href="##adjust"><i class="fa fa-adjust"></i> adjust</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tint|raindrop">
      <a onclick="selecteOneIcon(this)" href="##tint"><i class="fa fa-tint"></i> tint</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pencil-square-o|edit|write|edit|update">
      <a onclick="selecteOneIcon(this)" href="##pencil-square-o"><i class="fa fa-pencil-square-o"></i> pencil-square-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="share-square-o|social|send">
      <a onclick="selecteOneIcon(this)" href="##share-square-o"><i class="fa fa-share-square-o"></i> share-square-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="check-square-o|todo|done|agree|accept|confirm">
      <a onclick="selecteOneIcon(this)" href="##check-square-o"><i class="fa fa-check-square-o"></i> check-square-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrows|move|reorder|resize">
      <a onclick="selecteOneIcon(this)" href="##arrows"><i class="fa fa-arrows"></i> arrows</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="step-backward|rewind|previous|beginning|start|first">
      <a onclick="selecteOneIcon(this)" href="##step-backward"><i class="fa fa-step-backward"></i> step-backward</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="fast-backward|rewind|previous|beginning|start|first">
      <a onclick="selecteOneIcon(this)" href="##fast-backward"><i class="fa fa-fast-backward"></i> fast-backward</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="backward|rewind|previous">
      <a onclick="selecteOneIcon(this)" href="##backward"><i class="fa fa-backward"></i> backward</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="play|start|playing|music|sound">
      <a onclick="selecteOneIcon(this)" href="##play"><i class="fa fa-play"></i> play</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pause|wait">
      <a onclick="selecteOneIcon(this)" href="##pause"><i class="fa fa-pause"></i> pause</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="stop|block|box|square">
      <a onclick="selecteOneIcon(this)" href="##stop"><i class="fa fa-stop"></i> stop</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="forward|forward|next">
      <a onclick="selecteOneIcon(this)" href="##forward"><i class="fa fa-forward"></i> forward</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="fast-forward|next|end|last">
      <a onclick="selecteOneIcon(this)" href="##fast-forward"><i class="fa fa-fast-forward"></i> fast-forward</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="step-forward|next|end|last">
      <a onclick="selecteOneIcon(this)" href="##step-forward"><i class="fa fa-step-forward"></i> step-forward</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="eject">
      <a onclick="selecteOneIcon(this)" href="##eject"><i class="fa fa-eject"></i> eject</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chevron-left|bracket|previous|back">
      <a onclick="selecteOneIcon(this)" href="##chevron-left"><i class="fa fa-chevron-left"></i> chevron-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chevron-right|bracket|next|forward">
      <a onclick="selecteOneIcon(this)" href="##chevron-right"><i class="fa fa-chevron-right"></i> chevron-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="plus-circle|add|new|create|expand">
      <a onclick="selecteOneIcon(this)" href="##plus-circle"><i class="fa fa-plus-circle"></i> plus-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="minus-circle|delete|remove|trash|hide">
      <a onclick="selecteOneIcon(this)" href="##minus-circle"><i class="fa fa-minus-circle"></i> minus-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="times-circle|close|exit|x">
      <a onclick="selecteOneIcon(this)" href="##times-circle"><i class="fa fa-times-circle"></i> times-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="check-circle|todo|done|agree|accept|confirm">
      <a onclick="selecteOneIcon(this)" href="##check-circle"><i class="fa fa-check-circle"></i> check-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="question-circle|help|information|unknown|support">
      <a onclick="selecteOneIcon(this)" href="##question-circle"><i class="fa fa-question-circle"></i> question-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="info-circle|help|information|more|details">
      <a onclick="selecteOneIcon(this)" href="##info-circle"><i class="fa fa-info-circle"></i> info-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="crosshairs|picker">
      <a onclick="selecteOneIcon(this)" href="##crosshairs"><i class="fa fa-crosshairs"></i> crosshairs</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="times-circle-o|close|exit|x">
      <a onclick="selecteOneIcon(this)" href="##times-circle-o"><i class="fa fa-times-circle-o"></i> times-circle-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="check-circle-o|todo|done|agree|accept|confirm">
      <a onclick="selecteOneIcon(this)" href="##check-circle-o"><i class="fa fa-check-circle-o"></i> check-circle-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="ban|block|abort">
      <a onclick="selecteOneIcon(this)" href="##ban"><i class="fa fa-ban"></i> ban</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##arrow-left"><i class="fa fa-arrow-left"></i> arrow-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-right|next|forward">
      <a onclick="selecteOneIcon(this)" href="##arrow-right"><i class="fa fa-arrow-right"></i> arrow-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-up">
      <a onclick="selecteOneIcon(this)" href="##arrow-up"><i class="fa fa-arrow-up"></i> arrow-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-down|download">
      <a onclick="selecteOneIcon(this)" href="##arrow-down"><i class="fa fa-arrow-down"></i> arrow-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="share|mail-forward">
      <a onclick="selecteOneIcon(this)" href="##share"><i class="fa fa-share"></i> share</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="expand|enlarge|bigger|resize">
      <a onclick="selecteOneIcon(this)" href="##expand"><i class="fa fa-expand"></i> expand</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="compress|combine|merge|smaller">
      <a onclick="selecteOneIcon(this)" href="##compress"><i class="fa fa-compress"></i> compress</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="plus|add|new|create|expand">
      <a onclick="selecteOneIcon(this)" href="##plus"><i class="fa fa-plus"></i> plus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="minus|hide|minify|delete|remove|trash|hide|collapse">
      <a onclick="selecteOneIcon(this)" href="##minus"><i class="fa fa-minus"></i> minus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="asterisk|details">
      <a onclick="selecteOneIcon(this)" href="##asterisk"><i class="fa fa-asterisk"></i> asterisk</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="exclamation-circle|warning|error|problem|notification|alert">
      <a onclick="selecteOneIcon(this)" href="##exclamation-circle"><i class="fa fa-exclamation-circle"></i> exclamation-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="gift|present">
      <a onclick="selecteOneIcon(this)" href="##gift"><i class="fa fa-gift"></i> gift</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="leaf|eco|nature">
      <a onclick="selecteOneIcon(this)" href="##leaf"><i class="fa fa-leaf"></i> leaf</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="fire|flame|hot|popular">
      <a onclick="selecteOneIcon(this)" href="##fire"><i class="fa fa-fire"></i> fire</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="eye|show|visible|views">
      <a onclick="selecteOneIcon(this)" href="##eye"><i class="fa fa-eye"></i> eye</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="eye-slash|toggle|show|hide|visible|visiblity|views">
      <a onclick="selecteOneIcon(this)" href="##eye-slash"><i class="fa fa-eye-slash"></i> eye-slash</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="exclamation-triangle|warning|warning|error|problem|notification|alert">
      <a onclick="selecteOneIcon(this)" href="##exclamation-triangle"><i class="fa fa-exclamation-triangle"></i> exclamation-triangle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="plane|travel|trip|location|destination|airplane|fly|mode">
      <a onclick="selecteOneIcon(this)" href="##plane"><i class="fa fa-plane"></i> plane</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="calendar|date|time|when">
      <a onclick="selecteOneIcon(this)" href="##calendar"><i class="fa fa-calendar"></i> calendar</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="random|sort">
      <a onclick="selecteOneIcon(this)" href="##random"><i class="fa fa-random"></i> random</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="comment|speech|notification|note">
      <a onclick="selecteOneIcon(this)" href="##comment"><i class="fa fa-comment"></i> comment</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="magnet">
      <a onclick="selecteOneIcon(this)" href="##magnet"><i class="fa fa-magnet"></i> magnet</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chevron-up">
      <a onclick="selecteOneIcon(this)" href="##chevron-up"><i class="fa fa-chevron-up"></i> chevron-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chevron-down">
      <a onclick="selecteOneIcon(this)" href="##chevron-down"><i class="fa fa-chevron-down"></i> chevron-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="retweet|refresh|reload|share">
      <a onclick="selecteOneIcon(this)" href="##retweet"><i class="fa fa-retweet"></i> retweet</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="shopping-cart|checkout|buy|purchase|payment">
      <a onclick="selecteOneIcon(this)" href="##shopping-cart"><i class="fa fa-shopping-cart"></i> shopping-cart</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="folder">
      <a onclick="selecteOneIcon(this)" href="##folder"><i class="fa fa-folder"></i> folder</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="folder-open">
      <a onclick="selecteOneIcon(this)" href="##folder-open"><i class="fa fa-folder-open"></i> folder-open</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrows-v|resize">
      <a onclick="selecteOneIcon(this)" href="##arrows-v"><i class="fa fa-arrows-v"></i> arrows-v</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrows-h|resize">
      <a onclick="selecteOneIcon(this)" href="##arrows-h"><i class="fa fa-arrows-h"></i> arrows-h</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bar-chart|bar-chart-o|graph">
      <a onclick="selecteOneIcon(this)" href="##bar-chart"><i class="fa fa-bar-chart"></i> bar-chart</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="twitter-square|tweet|social network">
      <a onclick="selecteOneIcon(this)" href="##twitter-square"><i class="fa fa-twitter-square"></i> twitter-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="facebook-square|social network">
      <a onclick="selecteOneIcon(this)" href="##facebook-square"><i class="fa fa-facebook-square"></i> facebook-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="camera-retro|photo|picture|record">
      <a onclick="selecteOneIcon(this)" href="##camera-retro"><i class="fa fa-camera-retro"></i> camera-retro</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="key|unlock|password">
      <a onclick="selecteOneIcon(this)" href="##key"><i class="fa fa-key"></i> key</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cogs|gears|settings">
      <a onclick="selecteOneIcon(this)" href="##cogs"><i class="fa fa-cogs"></i> cogs</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="comments|conversation|notification|notes">
      <a onclick="selecteOneIcon(this)" href="##comments"><i class="fa fa-comments"></i> comments</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="thumbs-o-up|like|approve|favorite|agree">
      <a onclick="selecteOneIcon(this)" href="##thumbs-o-up"><i class="fa fa-thumbs-o-up"></i> thumbs-o-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="thumbs-o-down|dislike|disapprove|disagree">
      <a onclick="selecteOneIcon(this)" href="##thumbs-o-down"><i class="fa fa-thumbs-o-down"></i> thumbs-o-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="star-half|award|achievement|rating|score">
      <a onclick="selecteOneIcon(this)" href="##star-half"><i class="fa fa-star-half"></i> star-half</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="heart-o|love|like|favorite">
      <a onclick="selecteOneIcon(this)" href="##heart-o"><i class="fa fa-heart-o"></i> heart-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sign-out|log out|logout|leave|exit|arrow">
      <a onclick="selecteOneIcon(this)" href="##sign-out"><i class="fa fa-sign-out"></i> sign-out</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="linkedin-square">
      <a onclick="selecteOneIcon(this)" href="##linkedin-square"><i class="fa fa-linkedin-square"></i> linkedin-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="thumb-tack|marker|pin|location|coordinates">
      <a onclick="selecteOneIcon(this)" href="##thumb-tack"><i class="fa fa-thumb-tack"></i> thumb-tack</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="external-link|open|new">
      <a onclick="selecteOneIcon(this)" href="##external-link"><i class="fa fa-external-link"></i> external-link</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sign-in|enter|join|sign up|sign in|signin|signup|arrow">
      <a onclick="selecteOneIcon(this)" href="##sign-in"><i class="fa fa-sign-in"></i> sign-in</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="trophy|award|achievement|winner|game">
      <a onclick="selecteOneIcon(this)" href="##trophy"><i class="fa fa-trophy"></i> trophy</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="github-square|octocat">
      <a onclick="selecteOneIcon(this)" href="##github-square"><i class="fa fa-github-square"></i> github-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="upload|import">
      <a onclick="selecteOneIcon(this)" href="##upload"><i class="fa fa-upload"></i> upload</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="lemon-o">
      <a onclick="selecteOneIcon(this)" href="##lemon-o"><i class="fa fa-lemon-o"></i> lemon-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="phone|call|voice|number|support">
      <a onclick="selecteOneIcon(this)" href="##phone"><i class="fa fa-phone"></i> phone</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="square-o|block|square|box">
      <a onclick="selecteOneIcon(this)" href="##square-o"><i class="fa fa-square-o"></i> square-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bookmark-o|save">
      <a onclick="selecteOneIcon(this)" href="##bookmark-o"><i class="fa fa-bookmark-o"></i> bookmark-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="phone-square|call|voice|number|support">
      <a onclick="selecteOneIcon(this)" href="##phone-square"><i class="fa fa-phone-square"></i> phone-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="twitter|tweet|social network">
      <a onclick="selecteOneIcon(this)" href="##twitter"><i class="fa fa-twitter"></i> twitter</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="facebook|facebook-f|social network">
      <a onclick="selecteOneIcon(this)" href="##facebook"><i class="fa fa-facebook"></i> facebook</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="github|octocat">
      <a onclick="selecteOneIcon(this)" href="##github"><i class="fa fa-github"></i> github</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="unlock|protect|admin|password">
      <a onclick="selecteOneIcon(this)" href="##unlock"><i class="fa fa-unlock"></i> unlock</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="credit-card|money|buy|debit|checkout|purchase|payment">
      <a onclick="selecteOneIcon(this)" href="##credit-card"><i class="fa fa-credit-card"></i> credit-card</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="rss|feed|blog">
      <a onclick="selecteOneIcon(this)" href="##rss"><i class="fa fa-rss"></i> rss</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="hdd-o|harddrive|hard drive|storage|save">
      <a onclick="selecteOneIcon(this)" href="##hdd-o"><i class="fa fa-hdd-o"></i> hdd-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bullhorn|announcement|share|broadcast|louder">
      <a onclick="selecteOneIcon(this)" href="##bullhorn"><i class="fa fa-bullhorn"></i> bullhorn</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bell|alert|reminder|notification">
      <a onclick="selecteOneIcon(this)" href="##bell"><i class="fa fa-bell"></i> bell</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="certificate|badge|star">
      <a onclick="selecteOneIcon(this)" href="##certificate"><i class="fa fa-certificate"></i> certificate</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="hand-o-right|point|right|next|forward">
      <a onclick="selecteOneIcon(this)" href="##hand-o-right"><i class="fa fa-hand-o-right"></i> hand-o-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="hand-o-left|point|left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##hand-o-left"><i class="fa fa-hand-o-left"></i> hand-o-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="hand-o-up|point">
      <a onclick="selecteOneIcon(this)" href="##hand-o-up"><i class="fa fa-hand-o-up"></i> hand-o-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="hand-o-down|point">
      <a onclick="selecteOneIcon(this)" href="##hand-o-down"><i class="fa fa-hand-o-down"></i> hand-o-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-circle-left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##arrow-circle-left"><i class="fa fa-arrow-circle-left"></i> arrow-circle-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-circle-right|next|forward">
      <a onclick="selecteOneIcon(this)" href="##arrow-circle-right"><i class="fa fa-arrow-circle-right"></i> arrow-circle-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-circle-up">
      <a onclick="selecteOneIcon(this)" href="##arrow-circle-up"><i class="fa fa-arrow-circle-up"></i> arrow-circle-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-circle-down|download">
      <a onclick="selecteOneIcon(this)" href="##arrow-circle-down"><i class="fa fa-arrow-circle-down"></i> arrow-circle-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="globe|world|planet|map|place|travel|earth|global|translate|all|language|localize|location|coordinates|country">
      <a onclick="selecteOneIcon(this)" href="##globe"><i class="fa fa-globe"></i> globe</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="wrench|settings|fix|update">
      <a onclick="selecteOneIcon(this)" href="##wrench"><i class="fa fa-wrench"></i> wrench</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tasks|progress|loading|downloading|downloads|settings">
      <a onclick="selecteOneIcon(this)" href="##tasks"><i class="fa fa-tasks"></i> tasks</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="filter|funnel|options">
      <a onclick="selecteOneIcon(this)" href="##filter"><i class="fa fa-filter"></i> filter</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="briefcase|work|business|office|luggage|bag">
      <a onclick="selecteOneIcon(this)" href="##briefcase"><i class="fa fa-briefcase"></i> briefcase</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrows-alt|expand|enlarge|bigger|move|reorder|resize">
      <a onclick="selecteOneIcon(this)" href="##arrows-alt"><i class="fa fa-arrows-alt"></i> arrows-alt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="users|group|people|profiles|persons">
      <a onclick="selecteOneIcon(this)" href="##users"><i class="fa fa-users"></i> users</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="link|chain|chain">
      <a onclick="selecteOneIcon(this)" href="##link"><i class="fa fa-link"></i> link</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cloud|save">
      <a onclick="selecteOneIcon(this)" href="##cloud"><i class="fa fa-cloud"></i> cloud</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="flask|science|beaker|experimental|labs">
      <a onclick="selecteOneIcon(this)" href="##flask"><i class="fa fa-flask"></i> flask</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="scissors|cut">
      <a onclick="selecteOneIcon(this)" href="##scissors"><i class="fa fa-scissors"></i> scissors</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="files-o|copy|duplicate">
      <a onclick="selecteOneIcon(this)" href="##files-o"><i class="fa fa-files-o"></i> files-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="paperclip|attachment">
      <a onclick="selecteOneIcon(this)" href="##paperclip"><i class="fa fa-paperclip"></i> paperclip</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="floppy-o|save">
      <a onclick="selecteOneIcon(this)" href="##floppy-o"><i class="fa fa-floppy-o"></i> floppy-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="square|block|box">
      <a onclick="selecteOneIcon(this)" href="##square"><i class="fa fa-square"></i> square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bars|navicon|reorder|menu|drag|reorder|settings|list|ul|ol|checklist|todo|list">
      <a onclick="selecteOneIcon(this)" href="##bars"><i class="fa fa-bars"></i> bars</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="list-ul|ul|ol|checklist|todo|list">
      <a onclick="selecteOneIcon(this)" href="##list-ul"><i class="fa fa-list-ul"></i> list-ul</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="list-ol|ul|ol|checklist|list|todo|list|numbers">
      <a onclick="selecteOneIcon(this)" href="##list-ol"><i class="fa fa-list-ol"></i> list-ol</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="strikethrough">
      <a onclick="selecteOneIcon(this)" href="##strikethrough"><i class="fa fa-strikethrough"></i> strikethrough</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="underline">
      <a onclick="selecteOneIcon(this)" href="##underline"><i class="fa fa-underline"></i> underline</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="table|data|excel|spreadsheet">
      <a onclick="selecteOneIcon(this)" href="##table"><i class="fa fa-table"></i> table</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="magic|wizard|automatic|autocomplete">
      <a onclick="selecteOneIcon(this)" href="##magic"><i class="fa fa-magic"></i> magic</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="truck|shipping">
      <a onclick="selecteOneIcon(this)" href="##truck"><i class="fa fa-truck"></i> truck</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pinterest">
      <a onclick="selecteOneIcon(this)" href="##pinterest"><i class="fa fa-pinterest"></i> pinterest</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pinterest-square">
      <a onclick="selecteOneIcon(this)" href="##pinterest-square"><i class="fa fa-pinterest-square"></i> pinterest-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="google-plus-square|social network">
      <a onclick="selecteOneIcon(this)" href="##google-plus-square"><i class="fa fa-google-plus-square"></i> google-plus-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="google-plus|social network">
      <a onclick="selecteOneIcon(this)" href="##google-plus"><i class="fa fa-google-plus"></i> google-plus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="money|cash|money|buy|checkout|purchase|payment">
      <a onclick="selecteOneIcon(this)" href="##money"><i class="fa fa-money"></i> money</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="caret-down|more|dropdown|menu">
      <a onclick="selecteOneIcon(this)" href="##caret-down"><i class="fa fa-caret-down"></i> caret-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="caret-up">
      <a onclick="selecteOneIcon(this)" href="##caret-up"><i class="fa fa-caret-up"></i> caret-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="caret-left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##caret-left"><i class="fa fa-caret-left"></i> caret-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="caret-right|next|forward">
      <a onclick="selecteOneIcon(this)" href="##caret-right"><i class="fa fa-caret-right"></i> caret-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="columns|split|panes">
      <a onclick="selecteOneIcon(this)" href="##columns"><i class="fa fa-columns"></i> columns</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort|unsorted|order">
      <a onclick="selecteOneIcon(this)" href="##sort"><i class="fa fa-sort"></i> sort</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort-desc|sort-down|dropdown|more|menu">
      <a onclick="selecteOneIcon(this)" href="##sort-desc"><i class="fa fa-sort-desc"></i> sort-desc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort-asc|sort-up">
      <a onclick="selecteOneIcon(this)" href="##sort-asc"><i class="fa fa-sort-asc"></i> sort-asc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="envelope">
      <a onclick="selecteOneIcon(this)" href="##envelope"><i class="fa fa-envelope"></i> envelope</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="linkedin">
      <a onclick="selecteOneIcon(this)" href="##linkedin"><i class="fa fa-linkedin"></i> linkedin</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="undo|rotate-left|back">
      <a onclick="selecteOneIcon(this)" href="##undo"><i class="fa fa-undo"></i> undo</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="gavel|legal">
      <a onclick="selecteOneIcon(this)" href="##gavel"><i class="fa fa-gavel"></i> gavel</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tachometer|dashboard">
      <a onclick="selecteOneIcon(this)" href="##tachometer"><i class="fa fa-tachometer"></i> tachometer</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="comment-o|notification|note">
      <a onclick="selecteOneIcon(this)" href="##comment-o"><i class="fa fa-comment-o"></i> comment-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="comments-o|conversation|notification|notes">
      <a onclick="selecteOneIcon(this)" href="##comments-o"><i class="fa fa-comments-o"></i> comments-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bolt|flash|lightning|weather">
      <a onclick="selecteOneIcon(this)" href="##bolt"><i class="fa fa-bolt"></i> bolt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sitemap|directory|hierarchy|organization">
      <a onclick="selecteOneIcon(this)" href="##sitemap"><i class="fa fa-sitemap"></i> sitemap</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="umbrella">
      <a onclick="selecteOneIcon(this)" href="##umbrella"><i class="fa fa-umbrella"></i> umbrella</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="clipboard|paste|copy">
      <a onclick="selecteOneIcon(this)" href="##clipboard"><i class="fa fa-clipboard"></i> clipboard</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="lightbulb-o|idea|inspiration">
      <a onclick="selecteOneIcon(this)" href="##lightbulb-o"><i class="fa fa-lightbulb-o"></i> lightbulb-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="exchange">
      <a onclick="selecteOneIcon(this)" href="##exchange"><i class="fa fa-exchange"></i> exchange</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cloud-download|import">
      <a onclick="selecteOneIcon(this)" href="##cloud-download"><i class="fa fa-cloud-download"></i> cloud-download</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cloud-upload|import">
      <a onclick="selecteOneIcon(this)" href="##cloud-upload"><i class="fa fa-cloud-upload"></i> cloud-upload</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="user-md|doctor|profile|medical|nurse">
      <a onclick="selecteOneIcon(this)" href="##user-md"><i class="fa fa-user-md"></i> user-md</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="stethoscope">
      <a onclick="selecteOneIcon(this)" href="##stethoscope"><i class="fa fa-stethoscope"></i> stethoscope</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="suitcase|trip|luggage|travel|move|baggage">
      <a onclick="selecteOneIcon(this)" href="##suitcase"><i class="fa fa-suitcase"></i> suitcase</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bell-o|alert|reminder|notification">
      <a onclick="selecteOneIcon(this)" href="##bell-o"><i class="fa fa-bell-o"></i> bell-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="coffee|morning|mug|breakfast|tea|drink|cafe">
      <a onclick="selecteOneIcon(this)" href="##coffee"><i class="fa fa-coffee"></i> coffee</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cutlery|food|restaurant|spoon|knife|dinner|eat">
      <a onclick="selecteOneIcon(this)" href="##cutlery"><i class="fa fa-cutlery"></i> cutlery</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-text-o|new|page|pdf|document">
      <a onclick="selecteOneIcon(this)" href="##file-text-o"><i class="fa fa-file-text-o"></i> file-text-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="building-o|work|business|apartment|office">
      <a onclick="selecteOneIcon(this)" href="##building-o"><i class="fa fa-building-o"></i> building-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="hospital-o|building">
      <a onclick="selecteOneIcon(this)" href="##hospital-o"><i class="fa fa-hospital-o"></i> hospital-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="ambulance|support|help">
      <a onclick="selecteOneIcon(this)" href="##ambulance"><i class="fa fa-ambulance"></i> ambulance</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="medkit|first aid|firstaid|help|support">
      <a onclick="selecteOneIcon(this)" href="##medkit"><i class="fa fa-medkit"></i> medkit</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="fighter-jet|fly|plane|airplane|quick|fast|travel">
      <a onclick="selecteOneIcon(this)" href="##fighter-jet"><i class="fa fa-fighter-jet"></i> fighter-jet</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="beer|alcohol|stein|drink|mug|bar|liquor">
      <a onclick="selecteOneIcon(this)" href="##beer"><i class="fa fa-beer"></i> beer</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="h-square|hospital|hotel">
      <a onclick="selecteOneIcon(this)" href="##h-square"><i class="fa fa-h-square"></i> h-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="plus-square|add|new|create|expand">
      <a onclick="selecteOneIcon(this)" href="##plus-square"><i class="fa fa-plus-square"></i> plus-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angle-double-left|laquo|quote|previous|back">
      <a onclick="selecteOneIcon(this)" href="##angle-double-left"><i class="fa fa-angle-double-left"></i> angle-double-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angle-double-right|raquo|quote|next|forward">
      <a onclick="selecteOneIcon(this)" href="##angle-double-right"><i class="fa fa-angle-double-right"></i> angle-double-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angle-double-up">
      <a onclick="selecteOneIcon(this)" href="##angle-double-up"><i class="fa fa-angle-double-up"></i> angle-double-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angle-double-down">
      <a onclick="selecteOneIcon(this)" href="##angle-double-down"><i class="fa fa-angle-double-down"></i> angle-double-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angle-left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##angle-left"><i class="fa fa-angle-left"></i> angle-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angle-right|next|forward">
      <a onclick="selecteOneIcon(this)" href="##angle-right"><i class="fa fa-angle-right"></i> angle-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angle-up">
      <a onclick="selecteOneIcon(this)" href="##angle-up"><i class="fa fa-angle-up"></i> angle-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angle-down">
      <a onclick="selecteOneIcon(this)" href="##angle-down"><i class="fa fa-angle-down"></i> angle-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="desktop|monitor|screen|desktop|computer|demo|device">
      <a onclick="selecteOneIcon(this)" href="##desktop"><i class="fa fa-desktop"></i> desktop</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="laptop|demo|computer|device">
      <a onclick="selecteOneIcon(this)" href="##laptop"><i class="fa fa-laptop"></i> laptop</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tablet|ipad|device">
      <a onclick="selecteOneIcon(this)" href="##tablet"><i class="fa fa-tablet"></i> tablet</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="mobile|mobile-phone|cell phone|cellphone|text|call|iphone|number">
      <a onclick="selecteOneIcon(this)" href="##mobile"><i class="fa fa-mobile"></i> mobile</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="circle-o">
      <a onclick="selecteOneIcon(this)" href="##circle-o"><i class="fa fa-circle-o"></i> circle-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="quote-left">
      <a onclick="selecteOneIcon(this)" href="##quote-left"><i class="fa fa-quote-left"></i> quote-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="quote-right">
      <a onclick="selecteOneIcon(this)" href="##quote-right"><i class="fa fa-quote-right"></i> quote-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="spinner|loading|progress">
      <a onclick="selecteOneIcon(this)" href="##spinner"><i class="fa fa-spinner"></i> spinner</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="circle|dot|notification">
      <a onclick="selecteOneIcon(this)" href="##circle"><i class="fa fa-circle"></i> circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="reply|mail-reply">
      <a onclick="selecteOneIcon(this)" href="##reply"><i class="fa fa-reply"></i> reply</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="github-alt|octocat">
      <a onclick="selecteOneIcon(this)" href="##github-alt"><i class="fa fa-github-alt"></i> github-alt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="folder-o">
      <a onclick="selecteOneIcon(this)" href="##folder-o"><i class="fa fa-folder-o"></i> folder-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="folder-open-o">
      <a onclick="selecteOneIcon(this)" href="##folder-open-o"><i class="fa fa-folder-open-o"></i> folder-open-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="smile-o|emoticon|happy|approve|satisfied|rating">
      <a onclick="selecteOneIcon(this)" href="##smile-o"><i class="fa fa-smile-o"></i> smile-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="frown-o|emoticon|sad|disapprove|rating">
      <a onclick="selecteOneIcon(this)" href="##frown-o"><i class="fa fa-frown-o"></i> frown-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="meh-o|emoticon|rating|neutral">
      <a onclick="selecteOneIcon(this)" href="##meh-o"><i class="fa fa-meh-o"></i> meh-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="gamepad|controller">
      <a onclick="selecteOneIcon(this)" href="##gamepad"><i class="fa fa-gamepad"></i> gamepad</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="keyboard-o|type|input">
      <a onclick="selecteOneIcon(this)" href="##keyboard-o"><i class="fa fa-keyboard-o"></i> keyboard-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="flag-o|report|notification">
      <a onclick="selecteOneIcon(this)" href="##flag-o"><i class="fa fa-flag-o"></i> flag-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="flag-checkered|report|notification|notify">
      <a onclick="selecteOneIcon(this)" href="##flag-checkered"><i class="fa fa-flag-checkered"></i> flag-checkered</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="terminal|command|prompt|code">
      <a onclick="selecteOneIcon(this)" href="##terminal"><i class="fa fa-terminal"></i> terminal</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="code|html|brackets">
      <a onclick="selecteOneIcon(this)" href="##code"><i class="fa fa-code"></i> code</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="reply-all|mail-reply-all">
      <a onclick="selecteOneIcon(this)" href="##reply-all"><i class="fa fa-reply-all"></i> reply-all</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="star-half-o|star-half-empty|star-half-full|award|achievement|rating|score">
      <a onclick="selecteOneIcon(this)" href="##star-half-o"><i class="fa fa-star-half-o"></i> star-half-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="location-arrow|map|coordinates|location|address|place|where">
      <a onclick="selecteOneIcon(this)" href="##location-arrow"><i class="fa fa-location-arrow"></i> location-arrow</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="crop">
      <a onclick="selecteOneIcon(this)" href="##crop"><i class="fa fa-crop"></i> crop</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="code-fork|git|fork|vcs|svn|github|rebase|version|merge">
      <a onclick="selecteOneIcon(this)" href="##code-fork"><i class="fa fa-code-fork"></i> code-fork</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chain-broken|unlink|remove">
      <a onclick="selecteOneIcon(this)" href="##chain-broken"><i class="fa fa-chain-broken"></i> chain-broken</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="question|help|information|unknown|support">
      <a onclick="selecteOneIcon(this)" href="##question"><i class="fa fa-question"></i> question</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="info|help|information|more|details">
      <a onclick="selecteOneIcon(this)" href="##info"><i class="fa fa-info"></i> info</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="exclamation|warning|error|problem|notification|notify|alert">
      <a onclick="selecteOneIcon(this)" href="##exclamation"><i class="fa fa-exclamation"></i> exclamation</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="superscript|exponential">
      <a onclick="selecteOneIcon(this)" href="##superscript"><i class="fa fa-superscript"></i> superscript</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="subscript">
      <a onclick="selecteOneIcon(this)" href="##subscript"><i class="fa fa-subscript"></i> subscript</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="eraser">
      <a onclick="selecteOneIcon(this)" href="##eraser"><i class="fa fa-eraser"></i> eraser</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="puzzle-piece|addon|add-on|section">
      <a onclick="selecteOneIcon(this)" href="##puzzle-piece"><i class="fa fa-puzzle-piece"></i> puzzle-piece</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="microphone|record|voice|sound">
      <a onclick="selecteOneIcon(this)" href="##microphone"><i class="fa fa-microphone"></i> microphone</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="microphone-slash|record|voice|sound|mute">
      <a onclick="selecteOneIcon(this)" href="##microphone-slash"><i class="fa fa-microphone-slash"></i> microphone-slash</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="shield|award|achievement|winner">
      <a onclick="selecteOneIcon(this)" href="##shield"><i class="fa fa-shield"></i> shield</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="calendar-o|date|time|when">
      <a onclick="selecteOneIcon(this)" href="##calendar-o"><i class="fa fa-calendar-o"></i> calendar-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="fire-extinguisher">
      <a onclick="selecteOneIcon(this)" href="##fire-extinguisher"><i class="fa fa-fire-extinguisher"></i> fire-extinguisher</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="rocket|app">
      <a onclick="selecteOneIcon(this)" href="##rocket"><i class="fa fa-rocket"></i> rocket</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="maxcdn">
      <a onclick="selecteOneIcon(this)" href="##maxcdn"><i class="fa fa-maxcdn"></i> maxcdn</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chevron-circle-left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##chevron-circle-left"><i class="fa fa-chevron-circle-left"></i> chevron-circle-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chevron-circle-right|next|forward">
      <a onclick="selecteOneIcon(this)" href="##chevron-circle-right"><i class="fa fa-chevron-circle-right"></i> chevron-circle-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chevron-circle-up">
      <a onclick="selecteOneIcon(this)" href="##chevron-circle-up"><i class="fa fa-chevron-circle-up"></i> chevron-circle-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="chevron-circle-down|more|dropdown|menu">
      <a onclick="selecteOneIcon(this)" href="##chevron-circle-down"><i class="fa fa-chevron-circle-down"></i> chevron-circle-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="html5">
      <a onclick="selecteOneIcon(this)" href="##html5"><i class="fa fa-html5"></i> html5</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="css3|code">
      <a onclick="selecteOneIcon(this)" href="##css3"><i class="fa fa-css3"></i> css3</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="anchor|link">
      <a onclick="selecteOneIcon(this)" href="##anchor"><i class="fa fa-anchor"></i> anchor</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="unlock-alt|protect|admin|password">
      <a onclick="selecteOneIcon(this)" href="##unlock-alt"><i class="fa fa-unlock-alt"></i> unlock-alt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bullseye|target">
      <a onclick="selecteOneIcon(this)" href="##bullseye"><i class="fa fa-bullseye"></i> bullseye</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="ellipsis-h|dots">
      <a onclick="selecteOneIcon(this)" href="##ellipsis-h"><i class="fa fa-ellipsis-h"></i> ellipsis-h</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="ellipsis-v|dots">
      <a onclick="selecteOneIcon(this)" href="##ellipsis-v"><i class="fa fa-ellipsis-v"></i> ellipsis-v</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="rss-square|feed|blog">
      <a onclick="selecteOneIcon(this)" href="##rss-square"><i class="fa fa-rss-square"></i> rss-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="play-circle|start|playing">
      <a onclick="selecteOneIcon(this)" href="##play-circle"><i class="fa fa-play-circle"></i> play-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="ticket|movie|pass|support">
      <a onclick="selecteOneIcon(this)" href="##ticket"><i class="fa fa-ticket"></i> ticket</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="minus-square|hide|minify|delete|remove|trash|hide|collapse">
      <a onclick="selecteOneIcon(this)" href="##minus-square"><i class="fa fa-minus-square"></i> minus-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="minus-square-o|hide|minify|delete|remove|trash|hide|collapse">
      <a onclick="selecteOneIcon(this)" href="##minus-square-o"><i class="fa fa-minus-square-o"></i> minus-square-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="level-up">
      <a onclick="selecteOneIcon(this)" href="##level-up"><i class="fa fa-level-up"></i> level-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="level-down">
      <a onclick="selecteOneIcon(this)" href="##level-down"><i class="fa fa-level-down"></i> level-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="check-square|checkmark|done|todo|agree|accept|confirm">
      <a onclick="selecteOneIcon(this)" href="##check-square"><i class="fa fa-check-square"></i> check-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pencil-square|write|edit|update">
      <a onclick="selecteOneIcon(this)" href="##pencil-square"><i class="fa fa-pencil-square"></i> pencil-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="external-link-square|open|new">
      <a onclick="selecteOneIcon(this)" href="##external-link-square"><i class="fa fa-external-link-square"></i> external-link-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="share-square|social|send">
      <a onclick="selecteOneIcon(this)" href="##share-square"><i class="fa fa-share-square"></i> share-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="compass|safari|directory|menu|location">
      <a onclick="selecteOneIcon(this)" href="##compass"><i class="fa fa-compass"></i> compass</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="caret-square-o-down|toggle-down|more|dropdown|menu">
      <a onclick="selecteOneIcon(this)" href="##caret-square-o-down"><i class="fa fa-caret-square-o-down"></i> caret-square-o-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="caret-square-o-up|toggle-up">
      <a onclick="selecteOneIcon(this)" href="##caret-square-o-up"><i class="fa fa-caret-square-o-up"></i> caret-square-o-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="caret-square-o-right|toggle-right|next|forward">
      <a onclick="selecteOneIcon(this)" href="##caret-square-o-right"><i class="fa fa-caret-square-o-right"></i> caret-square-o-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="eur|euro">
      <a onclick="selecteOneIcon(this)" href="##eur"><i class="fa fa-eur"></i> eur</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="gbp">
      <a onclick="selecteOneIcon(this)" href="##gbp"><i class="fa fa-gbp"></i> gbp</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="usd|dollar">
      <a onclick="selecteOneIcon(this)" href="##usd"><i class="fa fa-usd"></i> usd</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="inr|rupee">
      <a onclick="selecteOneIcon(this)" href="##inr"><i class="fa fa-inr"></i> inr</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="jpy|cny|rmb|yen">
      <a onclick="selecteOneIcon(this)" href="##jpy"><i class="fa fa-jpy"></i> jpy</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="rub|ruble|rouble">
      <a onclick="selecteOneIcon(this)" href="##rub"><i class="fa fa-rub"></i> rub</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="krw|won">
      <a onclick="selecteOneIcon(this)" href="##krw"><i class="fa fa-krw"></i> krw</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="btc|bitcoin">
      <a onclick="selecteOneIcon(this)" href="##btc"><i class="fa fa-btc"></i> btc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file|new|page|pdf|document">
      <a onclick="selecteOneIcon(this)" href="##file"><i class="fa fa-file"></i> file</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-text|new|page|pdf|document">
      <a onclick="selecteOneIcon(this)" href="##file-text"><i class="fa fa-file-text"></i> file-text</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort-alpha-asc">
      <a onclick="selecteOneIcon(this)" href="##sort-alpha-asc"><i class="fa fa-sort-alpha-asc"></i> sort-alpha-asc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort-alpha-desc">
      <a onclick="selecteOneIcon(this)" href="##sort-alpha-desc"><i class="fa fa-sort-alpha-desc"></i> sort-alpha-desc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort-amount-asc">
      <a onclick="selecteOneIcon(this)" href="##sort-amount-asc"><i class="fa fa-sort-amount-asc"></i> sort-amount-asc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort-amount-desc">
      <a onclick="selecteOneIcon(this)" href="##sort-amount-desc"><i class="fa fa-sort-amount-desc"></i> sort-amount-desc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort-numeric-asc|numbers">
      <a onclick="selecteOneIcon(this)" href="##sort-numeric-asc"><i class="fa fa-sort-numeric-asc"></i> sort-numeric-asc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sort-numeric-desc|numbers">
      <a onclick="selecteOneIcon(this)" href="##sort-numeric-desc"><i class="fa fa-sort-numeric-desc"></i> sort-numeric-desc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="thumbs-up|like|favorite|approve|agree">
      <a onclick="selecteOneIcon(this)" href="##thumbs-up"><i class="fa fa-thumbs-up"></i> thumbs-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="thumbs-down|dislike|disapprove|disagree">
      <a onclick="selecteOneIcon(this)" href="##thumbs-down"><i class="fa fa-thumbs-down"></i> thumbs-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="youtube-square|video|film">
      <a onclick="selecteOneIcon(this)" href="##youtube-square"><i class="fa fa-youtube-square"></i> youtube-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="youtube|video|film">
      <a onclick="selecteOneIcon(this)" href="##youtube"><i class="fa fa-youtube"></i> youtube</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="xing">
      <a onclick="selecteOneIcon(this)" href="##xing"><i class="fa fa-xing"></i> xing</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="xing-square">
      <a onclick="selecteOneIcon(this)" href="##xing-square"><i class="fa fa-xing-square"></i> xing-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="youtube-play|start|playing">
      <a onclick="selecteOneIcon(this)" href="##youtube-play"><i class="fa fa-youtube-play"></i> youtube-play</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="dropbox">
      <a onclick="selecteOneIcon(this)" href="##dropbox"><i class="fa fa-dropbox"></i> dropbox</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="stack-overflow">
      <a onclick="selecteOneIcon(this)" href="##stack-overflow"><i class="fa fa-stack-overflow"></i> stack-overflow</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="instagram">
      <a onclick="selecteOneIcon(this)" href="##instagram"><i class="fa fa-instagram"></i> instagram</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="flickr">
      <a onclick="selecteOneIcon(this)" href="##flickr"><i class="fa fa-flickr"></i> flickr</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="adn">
      <a onclick="selecteOneIcon(this)" href="##adn"><i class="fa fa-adn"></i> adn</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bitbucket|git">
      <a onclick="selecteOneIcon(this)" href="##bitbucket"><i class="fa fa-bitbucket"></i> bitbucket</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bitbucket-square|git">
      <a onclick="selecteOneIcon(this)" href="##bitbucket-square"><i class="fa fa-bitbucket-square"></i> bitbucket-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tumblr">
      <a onclick="selecteOneIcon(this)" href="##tumblr"><i class="fa fa-tumblr"></i> tumblr</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tumblr-square">
      <a onclick="selecteOneIcon(this)" href="##tumblr-square"><i class="fa fa-tumblr-square"></i> tumblr-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="long-arrow-down">
      <a onclick="selecteOneIcon(this)" href="##long-arrow-down"><i class="fa fa-long-arrow-down"></i> long-arrow-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="long-arrow-up">
      <a onclick="selecteOneIcon(this)" href="##long-arrow-up"><i class="fa fa-long-arrow-up"></i> long-arrow-up</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="long-arrow-left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##long-arrow-left"><i class="fa fa-long-arrow-left"></i> long-arrow-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="long-arrow-right">
      <a onclick="selecteOneIcon(this)" href="##long-arrow-right"><i class="fa fa-long-arrow-right"></i> long-arrow-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="apple|osx">
      <a onclick="selecteOneIcon(this)" href="##apple"><i class="fa fa-apple"></i> apple</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="windows">
      <a onclick="selecteOneIcon(this)" href="##windows"><i class="fa fa-windows"></i> windows</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="android">
      <a onclick="selecteOneIcon(this)" href="##android"><i class="fa fa-android"></i> android</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="linux|tux">
      <a onclick="selecteOneIcon(this)" href="##linux"><i class="fa fa-linux"></i> linux</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="dribbble">
      <a onclick="selecteOneIcon(this)" href="##dribbble"><i class="fa fa-dribbble"></i> dribbble</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="skype">
      <a onclick="selecteOneIcon(this)" href="##skype"><i class="fa fa-skype"></i> skype</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="foursquare">
      <a onclick="selecteOneIcon(this)" href="##foursquare"><i class="fa fa-foursquare"></i> foursquare</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="trello">
      <a onclick="selecteOneIcon(this)" href="##trello"><i class="fa fa-trello"></i> trello</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="female|woman|user|person|profile">
      <a onclick="selecteOneIcon(this)" href="##female"><i class="fa fa-female"></i> female</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="male|man|user|person|profile">
      <a onclick="selecteOneIcon(this)" href="##male"><i class="fa fa-male"></i> male</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="gratipay|gittip|heart|like|favorite|love">
      <a onclick="selecteOneIcon(this)" href="##gratipay"><i class="fa fa-gratipay"></i> gratipay</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sun-o|weather|contrast|lighter|brighten|day">
      <a onclick="selecteOneIcon(this)" href="##sun-o"><i class="fa fa-sun-o"></i> sun-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="moon-o|night|darker|contrast">
      <a onclick="selecteOneIcon(this)" href="##moon-o"><i class="fa fa-moon-o"></i> moon-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="archive|box|storage">
      <a onclick="selecteOneIcon(this)" href="##archive"><i class="fa fa-archive"></i> archive</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bug|report">
      <a onclick="selecteOneIcon(this)" href="##bug"><i class="fa fa-bug"></i> bug</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="vk">
      <a onclick="selecteOneIcon(this)" href="##vk"><i class="fa fa-vk"></i> vk</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="weibo">
      <a onclick="selecteOneIcon(this)" href="##weibo"><i class="fa fa-weibo"></i> weibo</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="renren">
      <a onclick="selecteOneIcon(this)" href="##renren"><i class="fa fa-renren"></i> renren</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pagelines|leaf|leaves|tree|plant|eco|nature">
      <a onclick="selecteOneIcon(this)" href="##pagelines"><i class="fa fa-pagelines"></i> pagelines</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="stack-exchange">
      <a onclick="selecteOneIcon(this)" href="##stack-exchange"><i class="fa fa-stack-exchange"></i> stack-exchange</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-circle-o-right|next|forward">
      <a onclick="selecteOneIcon(this)" href="##arrow-circle-o-right"><i class="fa fa-arrow-circle-o-right"></i> arrow-circle-o-right</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="arrow-circle-o-left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##arrow-circle-o-left"><i class="fa fa-arrow-circle-o-left"></i> arrow-circle-o-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="caret-square-o-left|toggle-left|previous|back">
      <a onclick="selecteOneIcon(this)" href="##caret-square-o-left"><i class="fa fa-caret-square-o-left"></i> caret-square-o-left</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="dot-circle-o|target|bullseye|notification">
      <a onclick="selecteOneIcon(this)" href="##dot-circle-o"><i class="fa fa-dot-circle-o"></i> dot-circle-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="wheelchair|handicap|person|accessibility|accessibile">
      <a onclick="selecteOneIcon(this)" href="##wheelchair"><i class="fa fa-wheelchair"></i> wheelchair</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="vimeo-square">
      <a onclick="selecteOneIcon(this)" href="##vimeo-square"><i class="fa fa-vimeo-square"></i> vimeo-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="try|turkish-lira">
      <a onclick="selecteOneIcon(this)" href="##try"><i class="fa fa-try"></i> try</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="plus-square-o|add|new|create|expand">
      <a onclick="selecteOneIcon(this)" href="##plus-square-o"><i class="fa fa-plus-square-o"></i> plus-square-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="space-shuttle">
      <a onclick="selecteOneIcon(this)" href="##space-shuttle"><i class="fa fa-space-shuttle"></i> space-shuttle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="slack">
      <a onclick="selecteOneIcon(this)" href="##slack"><i class="fa fa-slack"></i> slack</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="envelope-square">
      <a onclick="selecteOneIcon(this)" href="##envelope-square"><i class="fa fa-envelope-square"></i> envelope-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="wordpress">
      <a onclick="selecteOneIcon(this)" href="##wordpress"><i class="fa fa-wordpress"></i> wordpress</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="openid">
      <a onclick="selecteOneIcon(this)" href="##openid"><i class="fa fa-openid"></i> openid</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="university|institution|bank">
      <a onclick="selecteOneIcon(this)" href="##university"><i class="fa fa-university"></i> university</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="graduation-cap|mortar-board">
      <a onclick="selecteOneIcon(this)" href="##graduation-cap"><i class="fa fa-graduation-cap"></i> graduation-cap</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="yahoo">
      <a onclick="selecteOneIcon(this)" href="##yahoo"><i class="fa fa-yahoo"></i> yahoo</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="google">
      <a onclick="selecteOneIcon(this)" href="##google"><i class="fa fa-google"></i> google</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="reddit">
      <a onclick="selecteOneIcon(this)" href="##reddit"><i class="fa fa-reddit"></i> reddit</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="reddit-square">
      <a onclick="selecteOneIcon(this)" href="##reddit-square"><i class="fa fa-reddit-square"></i> reddit-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="stumbleupon-circle">
      <a onclick="selecteOneIcon(this)" href="##stumbleupon-circle"><i class="fa fa-stumbleupon-circle"></i> stumbleupon-circle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="stumbleupon">
      <a onclick="selecteOneIcon(this)" href="##stumbleupon"><i class="fa fa-stumbleupon"></i> stumbleupon</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="delicious">
      <a onclick="selecteOneIcon(this)" href="##delicious"><i class="fa fa-delicious"></i> delicious</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="digg">
      <a onclick="selecteOneIcon(this)" href="##digg"><i class="fa fa-digg"></i> digg</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pied-piper">
      <a onclick="selecteOneIcon(this)" href="##pied-piper"><i class="fa fa-pied-piper"></i> pied-piper</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pied-piper-alt">
      <a onclick="selecteOneIcon(this)" href="##pied-piper-alt"><i class="fa fa-pied-piper-alt"></i> pied-piper-alt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="drupal">
      <a onclick="selecteOneIcon(this)" href="##drupal"><i class="fa fa-drupal"></i> drupal</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="joomla">
      <a onclick="selecteOneIcon(this)" href="##joomla"><i class="fa fa-joomla"></i> joomla</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="language">
      <a onclick="selecteOneIcon(this)" href="##language"><i class="fa fa-language"></i> language</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="fax">
      <a onclick="selecteOneIcon(this)" href="##fax"><i class="fa fa-fax"></i> fax</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="building">
      <a onclick="selecteOneIcon(this)" href="##building"><i class="fa fa-building"></i> building</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="child">
      <a onclick="selecteOneIcon(this)" href="##child"><i class="fa fa-child"></i> child</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="paw">
      <a onclick="selecteOneIcon(this)" href="##paw"><i class="fa fa-paw"></i> paw</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="spoon">
      <a onclick="selecteOneIcon(this)" href="##spoon"><i class="fa fa-spoon"></i> spoon</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cube">
      <a onclick="selecteOneIcon(this)" href="##cube"><i class="fa fa-cube"></i> cube</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cubes">
      <a onclick="selecteOneIcon(this)" href="##cubes"><i class="fa fa-cubes"></i> cubes</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="behance">
      <a onclick="selecteOneIcon(this)" href="##behance"><i class="fa fa-behance"></i> behance</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="behance-square">
      <a onclick="selecteOneIcon(this)" href="##behance-square"><i class="fa fa-behance-square"></i> behance-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="steam">
      <a onclick="selecteOneIcon(this)" href="##steam"><i class="fa fa-steam"></i> steam</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="steam-square">
      <a onclick="selecteOneIcon(this)" href="##steam-square"><i class="fa fa-steam-square"></i> steam-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="recycle">
      <a onclick="selecteOneIcon(this)" href="##recycle"><i class="fa fa-recycle"></i> recycle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="car|automobile|vehicle">
      <a onclick="selecteOneIcon(this)" href="##car"><i class="fa fa-car"></i> car</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="taxi|cab|vehicle">
      <a onclick="selecteOneIcon(this)" href="##taxi"><i class="fa fa-taxi"></i> taxi</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tree">
      <a onclick="selecteOneIcon(this)" href="##tree"><i class="fa fa-tree"></i> tree</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="spotify">
      <a onclick="selecteOneIcon(this)" href="##spotify"><i class="fa fa-spotify"></i> spotify</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="deviantart">
      <a onclick="selecteOneIcon(this)" href="##deviantart"><i class="fa fa-deviantart"></i> deviantart</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="soundcloud">
      <a onclick="selecteOneIcon(this)" href="##soundcloud"><i class="fa fa-soundcloud"></i> soundcloud</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="database">
      <a onclick="selecteOneIcon(this)" href="##database"><i class="fa fa-database"></i> database</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-pdf-o">
      <a onclick="selecteOneIcon(this)" href="##file-pdf-o"><i class="fa fa-file-pdf-o"></i> file-pdf-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-word-o">
      <a onclick="selecteOneIcon(this)" href="##file-word-o"><i class="fa fa-file-word-o"></i> file-word-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-excel-o">
      <a onclick="selecteOneIcon(this)" href="##file-excel-o"><i class="fa fa-file-excel-o"></i> file-excel-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-powerpoint-o">
      <a onclick="selecteOneIcon(this)" href="##file-powerpoint-o"><i class="fa fa-file-powerpoint-o"></i> file-powerpoint-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-image-o|file-photo-o|file-picture-o">
      <a onclick="selecteOneIcon(this)" href="##file-image-o"><i class="fa fa-file-image-o"></i> file-image-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-archive-o|file-zip-o">
      <a onclick="selecteOneIcon(this)" href="##file-archive-o"><i class="fa fa-file-archive-o"></i> file-archive-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-audio-o|file-sound-o">
      <a onclick="selecteOneIcon(this)" href="##file-audio-o"><i class="fa fa-file-audio-o"></i> file-audio-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-video-o|file-movie-o">
      <a onclick="selecteOneIcon(this)" href="##file-video-o"><i class="fa fa-file-video-o"></i> file-video-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="file-code-o">
      <a onclick="selecteOneIcon(this)" href="##file-code-o"><i class="fa fa-file-code-o"></i> file-code-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="vine">
      <a onclick="selecteOneIcon(this)" href="##vine"><i class="fa fa-vine"></i> vine</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="codepen">
      <a onclick="selecteOneIcon(this)" href="##codepen"><i class="fa fa-codepen"></i> codepen</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="jsfiddle">
      <a onclick="selecteOneIcon(this)" href="##jsfiddle"><i class="fa fa-jsfiddle"></i> jsfiddle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="life-ring|life-bouy|life-buoy|life-saver|support">
      <a onclick="selecteOneIcon(this)" href="##life-ring"><i class="fa fa-life-ring"></i> life-ring</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="circle-o-notch">
      <a onclick="selecteOneIcon(this)" href="##circle-o-notch"><i class="fa fa-circle-o-notch"></i> circle-o-notch</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="rebel|ra">
      <a onclick="selecteOneIcon(this)" href="##rebel"><i class="fa fa-rebel"></i> rebel</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="empire|ge">
      <a onclick="selecteOneIcon(this)" href="##empire"><i class="fa fa-empire"></i> empire</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="git-square">
      <a onclick="selecteOneIcon(this)" href="##git-square"><i class="fa fa-git-square"></i> git-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="git">
      <a onclick="selecteOneIcon(this)" href="##git"><i class="fa fa-git"></i> git</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="hacker-news">
      <a onclick="selecteOneIcon(this)" href="##hacker-news"><i class="fa fa-hacker-news"></i> hacker-news</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tencent-weibo">
      <a onclick="selecteOneIcon(this)" href="##tencent-weibo"><i class="fa fa-tencent-weibo"></i> tencent-weibo</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="qq">
      <a onclick="selecteOneIcon(this)" href="##qq"><i class="fa fa-qq"></i> qq</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="weixin|wechat">
      <a onclick="selecteOneIcon(this)" href="##weixin"><i class="fa fa-weixin"></i> weixin</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="paper-plane|send">
      <a onclick="selecteOneIcon(this)" href="##paper-plane"><i class="fa fa-paper-plane"></i> paper-plane</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="paper-plane-o|send-o">
      <a onclick="selecteOneIcon(this)" href="##paper-plane-o"><i class="fa fa-paper-plane-o"></i> paper-plane-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="history">
      <a onclick="selecteOneIcon(this)" href="##history"><i class="fa fa-history"></i> history</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="circle-thin|genderless">
      <a onclick="selecteOneIcon(this)" href="##circle-thin"><i class="fa fa-circle-thin"></i> circle-thin</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="header">
      <a onclick="selecteOneIcon(this)" href="##header"><i class="fa fa-header"></i> header</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="paragraph">
      <a onclick="selecteOneIcon(this)" href="##paragraph"><i class="fa fa-paragraph"></i> paragraph</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sliders">
      <a onclick="selecteOneIcon(this)" href="##sliders"><i class="fa fa-sliders"></i> sliders</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="share-alt">
      <a onclick="selecteOneIcon(this)" href="##share-alt"><i class="fa fa-share-alt"></i> share-alt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="share-alt-square">
      <a onclick="selecteOneIcon(this)" href="##share-alt-square"><i class="fa fa-share-alt-square"></i> share-alt-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bomb">
      <a onclick="selecteOneIcon(this)" href="##bomb"><i class="fa fa-bomb"></i> bomb</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="futbol-o|soccer-ball-o">
      <a onclick="selecteOneIcon(this)" href="##futbol-o"><i class="fa fa-futbol-o"></i> futbol-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="tty">
      <a onclick="selecteOneIcon(this)" href="##tty"><i class="fa fa-tty"></i> tty</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="binoculars">
      <a onclick="selecteOneIcon(this)" href="##binoculars"><i class="fa fa-binoculars"></i> binoculars</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="plug">
      <a onclick="selecteOneIcon(this)" href="##plug"><i class="fa fa-plug"></i> plug</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="slideshare">
      <a onclick="selecteOneIcon(this)" href="##slideshare"><i class="fa fa-slideshare"></i> slideshare</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="twitch">
      <a onclick="selecteOneIcon(this)" href="##twitch"><i class="fa fa-twitch"></i> twitch</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="yelp">
      <a onclick="selecteOneIcon(this)" href="##yelp"><i class="fa fa-yelp"></i> yelp</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="newspaper-o">
      <a onclick="selecteOneIcon(this)" href="##newspaper-o"><i class="fa fa-newspaper-o"></i> newspaper-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="wifi">
      <a onclick="selecteOneIcon(this)" href="##wifi"><i class="fa fa-wifi"></i> wifi</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="calculator">
      <a onclick="selecteOneIcon(this)" href="##calculator"><i class="fa fa-calculator"></i> calculator</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="paypal">
      <a onclick="selecteOneIcon(this)" href="##paypal"><i class="fa fa-paypal"></i> paypal</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="google-wallet">
      <a onclick="selecteOneIcon(this)" href="##google-wallet"><i class="fa fa-google-wallet"></i> google-wallet</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cc-visa">
      <a onclick="selecteOneIcon(this)" href="##cc-visa"><i class="fa fa-cc-visa"></i> cc-visa</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cc-mastercard">
      <a onclick="selecteOneIcon(this)" href="##cc-mastercard"><i class="fa fa-cc-mastercard"></i> cc-mastercard</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cc-discover">
      <a onclick="selecteOneIcon(this)" href="##cc-discover"><i class="fa fa-cc-discover"></i> cc-discover</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cc-amex">
      <a onclick="selecteOneIcon(this)" href="##cc-amex"><i class="fa fa-cc-amex"></i> cc-amex</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cc-paypal">
      <a onclick="selecteOneIcon(this)" href="##cc-paypal"><i class="fa fa-cc-paypal"></i> cc-paypal</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cc-stripe">
      <a onclick="selecteOneIcon(this)" href="##cc-stripe"><i class="fa fa-cc-stripe"></i> cc-stripe</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bell-slash">
      <a onclick="selecteOneIcon(this)" href="##bell-slash"><i class="fa fa-bell-slash"></i> bell-slash</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bell-slash-o">
      <a onclick="selecteOneIcon(this)" href="##bell-slash-o"><i class="fa fa-bell-slash-o"></i> bell-slash-o</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="trash">
      <a onclick="selecteOneIcon(this)" href="##trash"><i class="fa fa-trash"></i> trash</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="copyright">
      <a onclick="selecteOneIcon(this)" href="##copyright"><i class="fa fa-copyright"></i> copyright</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="at">
      <a onclick="selecteOneIcon(this)" href="##at"><i class="fa fa-at"></i> at</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="eyedropper">
      <a onclick="selecteOneIcon(this)" href="##eyedropper"><i class="fa fa-eyedropper"></i> eyedropper</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="paint-brush">
      <a onclick="selecteOneIcon(this)" href="##paint-brush"><i class="fa fa-paint-brush"></i> paint-brush</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="birthday-cake">
      <a onclick="selecteOneIcon(this)" href="##birthday-cake"><i class="fa fa-birthday-cake"></i> birthday-cake</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="area-chart">
      <a onclick="selecteOneIcon(this)" href="##area-chart"><i class="fa fa-area-chart"></i> area-chart</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pie-chart">
      <a onclick="selecteOneIcon(this)" href="##pie-chart"><i class="fa fa-pie-chart"></i> pie-chart</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="line-chart">
      <a onclick="selecteOneIcon(this)" href="##line-chart"><i class="fa fa-line-chart"></i> line-chart</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="lastfm">
      <a onclick="selecteOneIcon(this)" href="##lastfm"><i class="fa fa-lastfm"></i> lastfm</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="lastfm-square">
      <a onclick="selecteOneIcon(this)" href="##lastfm-square"><i class="fa fa-lastfm-square"></i> lastfm-square</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="toggle-off">
      <a onclick="selecteOneIcon(this)" href="##toggle-off"><i class="fa fa-toggle-off"></i> toggle-off</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="toggle-on">
      <a onclick="selecteOneIcon(this)" href="##toggle-on"><i class="fa fa-toggle-on"></i> toggle-on</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bicycle|vehicle|bike">
      <a onclick="selecteOneIcon(this)" href="##bicycle"><i class="fa fa-bicycle"></i> bicycle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bus|vehicle">
      <a onclick="selecteOneIcon(this)" href="##bus"><i class="fa fa-bus"></i> bus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="ioxhost">
      <a onclick="selecteOneIcon(this)" href="##ioxhost"><i class="fa fa-ioxhost"></i> ioxhost</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="angellist">
      <a onclick="selecteOneIcon(this)" href="##angellist"><i class="fa fa-angellist"></i> angellist</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cc">
      <a onclick="selecteOneIcon(this)" href="##cc"><i class="fa fa-cc"></i> cc</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="ils|shekel|sheqel">
      <a onclick="selecteOneIcon(this)" href="##ils"><i class="fa fa-ils"></i> ils</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="meanpath">
      <a onclick="selecteOneIcon(this)" href="##meanpath"><i class="fa fa-meanpath"></i> meanpath</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="buysellads">
      <a onclick="selecteOneIcon(this)" href="##buysellads"><i class="fa fa-buysellads"></i> buysellads</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="connectdevelop">
      <a onclick="selecteOneIcon(this)" href="##connectdevelop"><i class="fa fa-connectdevelop"></i> connectdevelop</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="dashcube">
      <a onclick="selecteOneIcon(this)" href="##dashcube"><i class="fa fa-dashcube"></i> dashcube</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="forumbee">
      <a onclick="selecteOneIcon(this)" href="##forumbee"><i class="fa fa-forumbee"></i> forumbee</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="leanpub">
      <a onclick="selecteOneIcon(this)" href="##leanpub"><i class="fa fa-leanpub"></i> leanpub</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="sellsy">
      <a onclick="selecteOneIcon(this)" href="##sellsy"><i class="fa fa-sellsy"></i> sellsy</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="shirtsinbulk">
      <a onclick="selecteOneIcon(this)" href="##shirtsinbulk"><i class="fa fa-shirtsinbulk"></i> shirtsinbulk</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="simplybuilt">
      <a onclick="selecteOneIcon(this)" href="##simplybuilt"><i class="fa fa-simplybuilt"></i> simplybuilt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="skyatlas">
      <a onclick="selecteOneIcon(this)" href="##skyatlas"><i class="fa fa-skyatlas"></i> skyatlas</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cart-plus|add|shopping">
      <a onclick="selecteOneIcon(this)" href="##cart-plus"><i class="fa fa-cart-plus"></i> cart-plus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="cart-arrow-down|shopping">
      <a onclick="selecteOneIcon(this)" href="##cart-arrow-down"><i class="fa fa-cart-arrow-down"></i> cart-arrow-down</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="diamond|gem|gemstone">
      <a onclick="selecteOneIcon(this)" href="##diamond"><i class="fa fa-diamond"></i> diamond</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="ship|boat|sea">
      <a onclick="selecteOneIcon(this)" href="##ship"><i class="fa fa-ship"></i> ship</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="user-secret|whisper|spy|incognito">
      <a onclick="selecteOneIcon(this)" href="##user-secret"><i class="fa fa-user-secret"></i> user-secret</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="motorcycle|vehicle|bike">
      <a onclick="selecteOneIcon(this)" href="##motorcycle"><i class="fa fa-motorcycle"></i> motorcycle</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="street-view|map">
      <a onclick="selecteOneIcon(this)" href="##street-view"><i class="fa fa-street-view"></i> street-view</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="heartbeat|ekg">
      <a onclick="selecteOneIcon(this)" href="##heartbeat"><i class="fa fa-heartbeat"></i> heartbeat</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="venus|female">
      <a onclick="selecteOneIcon(this)" href="##venus"><i class="fa fa-venus"></i> venus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="mars|male">
      <a onclick="selecteOneIcon(this)" href="##mars"><i class="fa fa-mars"></i> mars</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="mercury|transgender">
      <a onclick="selecteOneIcon(this)" href="##mercury"><i class="fa fa-mercury"></i> mercury</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="transgender">
      <a onclick="selecteOneIcon(this)" href="##transgender"><i class="fa fa-transgender"></i> transgender</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="transgender-alt">
      <a onclick="selecteOneIcon(this)" href="##transgender-alt"><i class="fa fa-transgender-alt"></i> transgender-alt</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="venus-double">
      <a onclick="selecteOneIcon(this)" href="##venus-double"><i class="fa fa-venus-double"></i> venus-double</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="mars-double">
      <a onclick="selecteOneIcon(this)" href="##mars-double"><i class="fa fa-mars-double"></i> mars-double</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="venus-mars">
      <a onclick="selecteOneIcon(this)" href="##venus-mars"><i class="fa fa-venus-mars"></i> venus-mars</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="mars-stroke">
      <a onclick="selecteOneIcon(this)" href="##mars-stroke"><i class="fa fa-mars-stroke"></i> mars-stroke</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="mars-stroke-v">
      <a onclick="selecteOneIcon(this)" href="##mars-stroke-v"><i class="fa fa-mars-stroke-v"></i> mars-stroke-v</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="mars-stroke-h">
      <a onclick="selecteOneIcon(this)" href="##mars-stroke-h"><i class="fa fa-mars-stroke-h"></i> mars-stroke-h</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="neuter">
      <a onclick="selecteOneIcon(this)" href="##neuter"><i class="fa fa-neuter"></i> neuter</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="facebook-official">
      <a onclick="selecteOneIcon(this)" href="##facebook-official"><i class="fa fa-facebook-official"></i> facebook-official</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="pinterest-p">
      <a onclick="selecteOneIcon(this)" href="##pinterest-p"><i class="fa fa-pinterest-p"></i> pinterest-p</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="whatsapp">
      <a onclick="selecteOneIcon(this)" href="##whatsapp"><i class="fa fa-whatsapp"></i> whatsapp</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="server">
      <a onclick="selecteOneIcon(this)" href="##server"><i class="fa fa-server"></i> server</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="user-plus">
      <a onclick="selecteOneIcon(this)" href="##user-plus"><i class="fa fa-user-plus"></i> user-plus</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="user-times">
      <a onclick="selecteOneIcon(this)" href="##user-times"><i class="fa fa-user-times"></i> user-times</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="bed|hotel|travel">
      <a onclick="selecteOneIcon(this)" href="##bed"><i class="fa fa-bed"></i> bed</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="viacoin">
      <a onclick="selecteOneIcon(this)" href="##viacoin"><i class="fa fa-viacoin"></i> viacoin</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="train">
      <a onclick="selecteOneIcon(this)" href="##train"><i class="fa fa-train"></i> train</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="subway">
      <a onclick="selecteOneIcon(this)" href="##subway"><i class="fa fa-subway"></i> subway</a>
    </div>
    
    <div class="fa-hover col-md-3 col-sm-4 filter-icon"
      data-filter="medium">
      <a onclick="selecteOneIcon(this)" href="##medium"><i class="fa fa-medium"></i> medium</a>
    </div>
                        </div><!-- /.col -->
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
    <!-- /.modal-dialog -->
    </div>


          
    