 <?php
 // module/Userreq/view/userreq/userreq/index.phtml:
 $title = $this->translate('userreqpagetitle');
 $this->headTitle($title);
 ?>
            <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <?php echo $this->escapeHtml($title); ?>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
                        <li class="active"><?php echo $this->translate('userreqpagetitle');?></li>
                    </ol>
                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <div id="error" style="display: none" class="callout callout-danger">
                                        
                                    </div>
                                </div>
                                <div class="box-body">
                                    <table id="userreqDataTable" class="table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th><?php echo $this->translate('tableid');?></th>
                                                <th><?php echo $this->translate('tableusername');?></th>
                                                <th><?php echo $this->translate('tableemail');?></th>
                                                <th><?php echo $this->translate('tabledisplayname');?></th>
                                                <th><?php echo $this->translate('tablecountry');?></th>
                                                <th><?php echo $this->translate('tablepage');?></th>
                                                <th><?php echo $this->translate('tableoptions');?></th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    
                </section><!-- /.content -->
 
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
    	var datatable;
        function fulldata(){
            datatable = $('#userreqDataTable').DataTable({
            "destroy": true,
            "lengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]],
            "searching": true,
            "ordering": true,
            "order": [[ 0, "desc" ]],
            "processing": true,
            "ajax" : "<?php echo $this->url('Userreq', array('action'=>'getAll'));?>",
            "columnDefs" : [{
                            "targets": 0,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 1,
                            "data": "username",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 2,
                            "data": "email",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                    "targets": 3,
                    "data": "displayName",
                    "render": function ( data, type, full, meta ) {return data +" "+ full.displayName2;}
                 },{
                     "targets": 4,
                     "data": "country",
                     "render": function ( data, type, full, meta ) {return data.name +" "+ data.arname;}
                 },{
                     "targets": 5,
                     "data": "page_id",
                     "render": function ( data, type, full, meta ) {return data.name+"/"+ data.enname;}
                 },{
                            "targets": 6,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
                                    var activeicon='fa fa-close';
                                    var activemsg='Activate';
                                    if(full.active){
                                    activeicon='fa fa-check';
                                    activemsg='Deactivate';
                                    }
                                    
                                    return "<a rel='" + data + "' class='btn btn-xs accept' data-toggle='tooltip' data-placement='top' title='Accept'><i class='fa fa-check'></i></a>\n\
                                <a rel='"+ data +"' class='btn btn-xs delete' data-toggle='tooltip' data-placement='top' title='Delete'><i class='fa fa-trash'></i></a>";
                                }
                        }]
            });
        };
        
        fulldata();
         
        $('#userreqDataTable tbody').on('click', '.delete', function () {
            var data = $(this).attr('rel');
            var el = this;
            bootbox.confirm("<?php echo $this->translate('yesorno');?>", function(result) {
                if(result){
                    $.post(
                            "<?php echo $this->url('Userreq', array('action'=>'delete'));?>"+data,
                             function (data){
                                 //data = JSON.stringify(data);
                                 if(data.done == 'true'){
                                     //fulldata();
                                     datatable.row( $(el).parents('tr') )
					        .remove()
					        .draw(false);
                                 }else{
                                 $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                                     $('#error').show(150);
                                 }
                             }
                    );
                }
            }); 
        });
        $('#userreqDataTable tbody').on('click', '.accept', function () {
            var data = $(this).attr('rel');
            var el = this;
            $.post(
                    "<?php echo $this->url('Userreq', array('action'=>'accept'));?>"+data,
                     function (data){
                         if(data.done == 'true'){
                             fulldata();
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
     });

     <?php $this->inlineScript()->captureEnd() ?>


 