<?php
// module/Settings/view/settings/settings/add.phtml:

$title = 'Add new settings';
$this->headTitle($title);
?>
<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($title); ?>
        <small>This Is Page Countries</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i>Dashbord</a></li>
        <li><a href="<?php echo $this->url('Settings') ?>">Settings</a></li>
        <li class="active"><?php echo $this->escapeHtml($title); ?></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <!-- general form elements disabled -->
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
                </div><!-- /.box-header -->
                <div class="box-body">

                    <?php
                    $form->setAttribute('action', $this->url('Settings', array('action' => 'add')));
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('user'));
                    ?>
                    <div class="form-group">
                        <label for='title'>Title</label>
                        <?php
                        echo $this->formRow($form->get('title'));
                        ?>
                    </div>
                    
                    <div class="form-group">
                        <label for='artitle'>Arabic Title</label>
                        <?php
                        echo $this->formRow($form->get('artitle'));
                        ?>
                    </div>
                    
                    <div class="form-group">
                        <label for='image'>Image</label>
                        <?php
                        echo $this->formRow($form->get('image'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='settingslink'>Settings Link</label>
                        <?php
                        echo $this->formRow($form->get('settingslink'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='country'>Country</label>
                        <?php
                        echo $this->formRow($form->get('country'));
                        ?>
                    </div>

                    <div class="form-group">
                        <label for='content'>Content</label>
                        <?php
                        echo $this->formRow($form->get('content'));
                        ?>
                    </div>
                    
                    <div class="form-group">
                        <label for='arcontent'>Arabic Content</label>
                        <?php
                        echo $this->formRow($form->get('arcontent'));
                        ?>
                    </div>
                    
                    <div class="box-footer">
                        <?php
                        echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
