 <?php
 // module/Visit/view/visit/visit/index.phtml:
 $title = $this->translate('visitpagetitle');
 $this->headTitle($title);
 ?>
            <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <?php echo $this->escapeHtml($title); ?>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('visitpagetitle');?></a></li>
                        <li class="active"><?php echo $this->translate('visitpagetitle');?></li>
                    </ol>
                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <div id="error" style="display: none" class="callout callout-danger">
                                        
                                    </div>
                                    <p>
                                        <a href="<?php echo $this->url('Visit', array('action'=>'add'));?>"><?php echo $this->translate('add');?></a>
                                    </p>
                                </div>
                                <div class="box-body">
                                    <table id="visitDataTable" class="table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th><?php echo $this->translate('tableid');?></th>
                                                <th><?php echo $this->translate('tableip');?></th>
                                                <th><?php echo $this->translate('tabledate');?></th>
                                                <th><?php echo $this->translate('tableoptions');?></th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    
                </section><!-- /.content -->
 
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
    var datatable;
        function fulldata(){
            datatable = $('#visitDataTable').DataTable({
            "destroy": true,
            "lengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]],
            "searching": true,
            "ordering": true,
            "order": [[ 0, "desc" ]],
            "processing": true,
            "serverSide": true,
            "ajax" : "<?php echo $this->url('Visit', array('action'=>'getAllPages'));?>",
            "columnDefs" : [{
                            "targets": 0,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 1,
                            "data": "ip_address",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
			    "targets": 2,
                            "data": "visit_date",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 3,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
                                return "<a rel='"+ data +"' class='btn btn-xs delete' data-toggle='tooltip' data-placement='top' title='Delete'><i class='fa fa-trash'></i></a>";
                                }
                        }]
            });
        };
        
        fulldata();
         
        $('#visitDataTable tbody').on('click', '.delete', function () {
            var data = $(this).attr('rel');
            var el = this;
            bootbox.confirm("<?php echo $this->translate('yesorno');?>", function(result) {
                if(result){
                    $.post(
                            "<?php echo $this->url('Visit', array('action'=>'delete'));?>"+data,
                             function (data){
                                 //data = JSON.stringify(data);
                                 if(data.done == 'true'){
                                     //fulldata();
                                     datatable.row( $(el).parents('tr') )
					        .remove()
					        .draw(false);
                                 }else{
                                 $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                                     $('#error').show(150);
                                 }
                             }
                    );
                }
            }); 
        });
        
        $('#visitDataTable tbody').on('click', '.chstatus', function () {
            var data = $(this).attr('rel');
            $.post(
                    "<?php echo $this->url('Visit', array('action'=>'chstatus'));?>"+data,
                     function (data){
                         if(data.done == 'true'){
                             fulldata();
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
     });

     <?php $this->inlineScript()->captureEnd() ?>


 