<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Edite Permissions</h4>
        </div>
        <div class="modal-body">
            <!-- Main content -->
                    <p class="text-danger"></p>
                    
                        <a href='#' id='select-all'>Select All</a> /
                        <a href='#' id='deselect-all'>Deselect All</a>
                        <select multiple id="usersP" name="searchable[]">
                            <?php foreach ($users as $user) { ?>
                                <option value="<?php echo $user['id']; ?>"
                                <?php
                                foreach ($userroles as $userrole) {
                                    if ($user['id'] == $userrole['userid'])
                                        echo "selected='selected'";
                                }
                                ?> >
                                    <?php echo $user['username']; ?></option> 
                            <?php } ?>
                        </select>
                    
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
    <!-- /.modal-content -->
</div>
<!-- /.modal-dialog -->




<script type="text/javascript">

    (function ($) {
        $(function () {
            var noloop = true;
            $('#usersP').multiSelect({
                selectableHeader: "<div class='custom-header'> All Users </div>",
                selectionHeader: "<div class='custom-header'>User With Perm</div>",
                afterSelect: function (values) {
                    //this.qs1.cache();
                    //this.qs2.cache();
                    //alert("Select value: " + values);
                    $.ajax({
                        url: '<?php echo $this->url('Permissions', array('action' => 'add', 'context' => $context, 'id' => $id)); ?>/' + values,
                        type: 'post',
                        success: function (result) {
                            $('p.text-danger').html(result.message);
                            if (result.done != 'Done') {
                                if (noloop) {
                                    $('#usersP').multiSelect('deselect', values);
                                    noloop = false;
                                } else {
                                    noloop = true;
                                }
                            }
                        },
                    });
                },
                afterDeselect: function (values) {
                    //this.qs1.cache();
                    //this.qs2.cache();
                    //alert("Deselect value : " + values);
                    $.ajax({
                        url: '<?php echo $this->url('Permissions', array('action' => 'delete', 'context' => $context, 'id' => $id)); ?>/' + values,
                        type: 'post',
                        success: function (result) {
                            $('p.text-danger').html(result.message);
                            if (result.done != 'Done') {
                                if (noloop) {
                                    $('#usersP').multiSelect('select', values);
                                    noloop = false;
                                } else {
                                    noloop = true;
                                }
                            }
                        },
                    });
                }
            });
        });
        $('#select-all').click(function () {
            $('#usersP').multiSelect('select_all');
            return false;
        });
        $('#deselect-all').click(function () {
            $('#usersP').multiSelect('deselect_all');
            return false;
        });
    })(jQuery);
</script>
