<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('I2host'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                //->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                ->appendHttpEquiv('Content-Type', 'text/html;charset=utf8');
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.css'))
                ->prependStylesheet($this->basePath('fonts/font-awesome/css/font-awesome.css'))
                ->prependStylesheet($this->basePath('fonts/ionicons/css/ionicons.css'))
                ->prependStylesheet($this->basePath('plugins/datatables/css/dataTables.bootstrap.css'))
                ->prependStylesheet($this->basePath('plugins/multi-select/css/multi-select.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/skin-blue.css'))
                ->prependStylesheet($this->basePath('css/custom.css'))
        ?>
    </head>
    <body class="skin-blue">
        <div class="wrapper">
            <!-- Main Header -->
            <header class="main-header">
                <!-- Logo -->
                <a class="logo" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/></a>
                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- Messages: style can be found in dropdown.less-->
                            <li class="dropdown messages-menu">
                                <!-- Menu toggle button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="label label-success">4</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">You have 4 messages</li>
                                    <li>
                                        <!-- inner menu: contains the messages -->
                                        <ul class="menu">
                                            <li><!-- start message -->
                                                <a href="#">
                                                    <div class="pull-left">
                                                        <!-- User Image -->
                                                        <img class="img-circle" src="<?php echo $this->zfcUserIdentity()->getPhoto();?>"/>
                                                    </div>
                                                    <!-- Message title and timestamp -->
                                                    <h4>                            
                                                        Support Team
                                                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                                    </h4>
                                                    <!-- The message -->
                                                    <p>Why not buy a new awesome theme?</p>
                                                </a>
                                            </li><!-- end message -->                      
                                        </ul><!-- /.menu -->
                                    </li>
                                    <li class="footer"><a href="#">See All Messages</a></li>
                                </ul>
                            </li><!-- /.messages-menu -->

                            <!-- Notifications Menu -->
                            <li class="dropdown notifications-menu">
                                <!-- Menu toggle button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-bell-o"></i>
                                    <span class="label label-warning">10</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">You have 10 notifications</li>
                                    <li>
                                        <!-- Inner Menu: contains the notifications -->
                                        <ul class="menu">
                                            <li><!-- start notification -->
                                                <a href="#">
                                                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                                </a>
                                            </li><!-- end notification -->                      
                                        </ul>
                                    </li>
                                    <li class="footer"><a href="#">View all</a></li>
                                </ul>
                            </li>
                            <!-- Tasks Menu -->
                            <li class="dropdown tasks-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-flag-o"></i>
                                    <span class="label label-danger">9</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">You have 9 tasks</li>
                                    <li>
                                        <!-- Inner menu: contains the tasks -->
                                        <ul class="menu">
                                            <li><!-- Task item -->
                                                <a href="#">
                                                    <!-- Task title and progress text -->
                                                    <h3>
                                                        Design some buttons
                                                        <small class="pull-right">20%</small>
                                                    </h3>
                                                    <!-- The progress bar -->
                                                    <div class="progress xs">
                                                        <!-- Change the css width attribute to simulate progress -->
                                                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                            <span class="sr-only">20% Complete</span>
                                                        </div>
                                                    </div>
                                                </a>
                                            </li><!-- end task item -->                      
                                        </ul>
                                    </li>
                                    <li class="footer">
                                        <a href="#">View all tasks</a>
                                    </li>
                                </ul>
                            </li>
                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    
                                    <img style="max-height: 20px ; width: 20px; height: 20px" class="img-circle" src="<?php echo $this->zfcUserIdentity()->getPhoto();?>"/>
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs"><?php echo $this->zfcUserDisplayName() ?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header">
                                        <img class="img-circle" src="<?php echo $this->zfcUserIdentity()->getPhoto();?>"/>
                                        <p>
                                            <?php echo $this->zfcUserDisplayName() ?>! - Web Developer
                                            <small><?php echo $this->zfcUserIdentity()->getEmail(); ?></small>
                                        </p>
                                    </li>
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="<?php echo $this->url('Userprofile');?>" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="<?php echo $this->url('zfcuser/logout') ?>" class="btn btn-default btn-flat"><?php echo $this->translate('Sign Out'); ?></a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">

                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">

                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel">
                        <div class="pull-left image">
                             <img class="img-circle" src="<?php echo $this->zfcUserIdentity()->getPhoto();?>"/>
                        </div>
                        <div class="pull-left info">
                            <p><?php echo $this->zfcUserDisplayName() ?></p>
                            <!-- Status -->
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>

                    <!-- Sidebar Menu -->
                    <?php
                    $adminUser= $this->zfcUserIdentity()->getIsAdmin();
                    ?>
                    <ul class="sidebar-menu">
                        <!-- <li class="header">HEADER</li> -->
                        <!-- Optionally, you can add icons to the links -->
                        <li><a href="<?php echo $this->url('home') ?>"><i class="ion-ios-speedometer-outline"></i> <span><?php echo $this->translate('dashbord');?></span> </a></li>
                        <?php if($adminUser):?>
                        <li><a href="<?php echo $this->url('Users') ?>"><i class="ion-ios-people-outline"></i> <span><?php echo $this->translate('userspagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Countries') ?>"><i class="ion-ios-people-outline"></i> <span><?php echo $this->translate('countrypagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Pages') ?>"><i class="fa fa-files-o"></i> <span><?php echo $this->translate('pagespagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Programs') ?>"><i class="ion-ios-paper-outline"></i> <span><?php echo $this->translate('programspagetitle');?></span> </a></li>
                        <?php endif;?>
                        <li><a href="<?php echo $this->url('News') ?>"><i class="ion-ios-paper-outline"></i> <span><?php echo $this->translate('newspagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Video') ?>"><i class="ion-ios-videocam"></i> <span><?php echo $this->translate('videopagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Audio') ?>"><i class="ion-headphone"></i> <span><?php echo $this->translate('audiopagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Photo') ?>"><i class="ion-camera"></i> <span><?php echo $this->translate('imagepagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Comment') ?>"><i class="ion-chatboxes"></i> <span><?php echo $this->translate('commentspagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Visit') ?>"><i class="ion-chatboxes"></i> <span><?php echo $this->translate('visitpagetitle');?></span> </a></li>
                        <li><a href="<?php echo $this->url('Advertisement') ?>"><i class="fa fa-files-o"></i> <span><?php echo $this->translate('advertisementpagetitle');?></span> </a></li>
                        <?php if($adminUser):?>
                        <li><a href="<?php echo $this->url('Settings') ?>"><i class="fa fa-files-o"></i> <span><?php echo $this->translate('settingspagetitle');?></span> </i></a></li>
                        <?php endif;?>
                        
                    </ul><!-- /.sidebar-menu -->
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <?php echo $this->content; ?>
            </div><!-- /.content-wrapper -->

            <!-- Main Footer -->
            <footer class="main-footer">
                <!-- To the right -->
                <div class="pull-right hidden-xs">
                    Anything you want
                </div>
                <!-- Default to the left --> 
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>

        </div><!-- ./wrapper -->

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('plugins/multi-select/js/jquery.multi-select.js'))
                ->prependFile($this->basePath('plugins/datatables/js/dataTables.bootstrap.js'))
                ->prependFile($this->basePath('plugins/datatables/js/jquery.dataTables.js'))
                //->prependFile($this->basePath('js/error-massages.js'))
                ->prependFile($this->basePath('js/validator.js'))
                ->prependFile($this->basePath('js/app.js'))
                ->prependFile($this->basePath('js/jquery.form.js'))
                ->prependFile($this->basePath('js/bootbox.js'))
                ->prependFile($this->basePath('js/bootstrap.js'))
                ->prependFile($this->basePath('js/jquery-ui-1.10.3.js'))
                ->prependFile($this->basePath('js/jQuery-2.1.3.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        <!-- Optionally, you can add Slimscroll and FastClick plugins. 
              Both of these plugins are recommended to enhance the 
              user experience -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
