 <?php
 // module/Comment/view/comment/comment/index.phtml:
 $title = 'My comment';
 $this->headTitle($title);
 ?>
            <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <?php echo $this->escapeHtml($title); ?>
                        <small>This Is Page Comment</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i>Dashbord</a></li>
                        <li class="active">Comment</li>
                    </ol>
                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <div id="error" style="display: none" class="callout callout-danger">
                                        
                                    </div>
                                    <!--<p>
                                        <a href="<?php echo $this->url('Comment', array('action'=>'add'));?>">Add new Comment</a>
                                    </p>-->
                                </div>
                                <div class="box-body">
                                    <table id="commentDataTable" class="table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <!-- <th>Title</th> -->
                                                <th>Content</th>
                                                <th>User</th>
                                                <th>Date</th>
                                                <th>Status</th>
                                                <th>Options</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    
                </section><!-- /.content -->
 
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
    	var datatable;
        function fulldata(){
           datatable = $('#commentDataTable').DataTable({
	            "destroy": true,
	            "lengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]],
	            "searching": true,
	            "ordering": true,
	            "order": [[ 0, "desc" ]],
	            "processing": true,
	            "ajax" : "<?php echo $this->url('viewComments', array('action'=>'getComments','type'=>$this->type,'id'=>$this->id));?>",
	            "columnDefs" : [{
                            "targets": 0,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 1,
                            "data": "content",
                            "render": function ( data, type, full, meta ) {
                                            return data;
                                        }
                                    },{
			    "targets": 2,
                            "data": "username",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 3,
                            "data": "comment_date",
                            "render": function ( data, type, full, meta ) {
					return data;
                                    }
				},{
                            "targets": 4,
                            "data": "active",
                            "render": function ( data, type, full, meta ) {
                                        var activeicon='fa fa-close';
                                        var activemsg='Activate';
                                        if(data){
                                            activeicon='fa fa-check';
                                            activemsg='Deactivate';
                                        }
                                        return "<a rel='" + full.id + "' class='btn btn-xs chstatus' data-toggle='tooltip' data-placement='top' title='"+ activemsg +"'><i class='"+ activeicon +"'></i></a>";
                                    }
				},{
                            "targets": 5,
                            "data": "id",
                            "render": function ( data, type, full, meta ) {
                                return "<a rel='"+ data +"' class='btn btn-xs delete' data-toggle='tooltip' data-placement='top' title='Delete'><i class='fa fa-trash'></i></a>\n\
                                <a href='<?php echo $this->url('Comment', array('action'=>'edit'));?>"+ data +"' class='btn btn-xs' data-toggle='tooltip' data-placement='top' title='Edit'><i class='fa fa-edit'></i></a>";
                                }
                        }]
            });
        };
        
        fulldata();
         
        $('#commentDataTable tbody').on('click', '.delete', function () {
            var data = $(this).attr('rel');
            var el = this;
            bootbox.confirm("Are you sure?", function(result) {
                if(result){
                    $.post(
                            "<?php echo $this->url('Comment', array('action'=>'delete'));?>"+data,
                             function (data){
                                 //data = JSON.stringify(data);
                                 if(data.done == 'true'){
                                     //fulldata();
                                     datatable.row( $(el).parents('tr') )
					        .remove()
					        .draw(false);
                                 }else{
                                 $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                                     $('#error').show(150);
                                 }
                             }
                    );
                }
            }); 
        });
        
        $('#commentDataTable tbody').on('click', '.chstatus', function () {
            var data = $(this).attr('rel');
            var el = this;
            $.post(
                    "<?php echo $this->url('Comment', array('action'=>'chstatus'));?>"+data,
                     function (data){
                         if(data.done == 'true'){
                             //fulldata();
                             if( $(el).attr('title') == "Activate"){
                             	$(el).attr('title', "Deactivate");
                             	$(el).find(".fa.fa-close").attr('class','fa fa-check');
                             }else{
                             	$(el).attr('title', "Activate");
                             	$(el).find(".fa.fa-check").attr('class','fa fa-close');
                             }
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
     });

     <?php $this->inlineScript()->captureEnd() ?>


 