<?php
$title = $this->translate('edit')." ".$this->translate('commentspagetitle');
$this->headTitle($title);
?>
<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($title); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
        <li><a href="<?php echo $this->url('Comment') ?>"><?php echo $this->translate('commentspagetitle');?></a></li>
        <li class="active"><?php echo $this->escapeHtml($title); ?></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <!-- general form elements disabled -->
            <div class="box box-primary">

                <div class="box-body">

                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('Comment', array('action' => 'edit', 'id' => $this->id,)));
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('comment_date'));
                    ?>
                    <div class="form-group">
                        <label for='title'><?php echo $this->translate('titleform');?></label>
                        <?php
                        echo $this->formRow($form->get('title'));
                        ?>
                    </div>
                    
                    <div class="form-group">
                        <label for='content'><?php echo $this->translate('contentform');?></label>
                        <?php
                        echo $this->formRow($form->get('content'));
                        ?>
                    </div>
                    
                    <div class="form-group">
                        <label for='username'><?php echo $this->translate('usernameform');?></label>
                        <?php
                        echo $this->formRow($form->get('username'));
                        ?>
                    </div>
                    
                    <div class="form-group">
                        <label for='type'><?php echo $this->translate('typeform');?></label>
                        <?php
                        echo $this->formRow($form->get('type'));
                        ?>
                    </div>
                    
                    <div class="form-group">
                        <label for='type_id'><?php echo $this->translate('typeidform');?></label>
                        <?php
                        echo $this->formRow($form->get('type_id'));
                        ?>
                    </div>
                    
                    <div class="box-footer">
                        <?php
                        echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
