 <?php
 // module/Comment/view/comment/comment/index.phtml:
 $title = $this->translate('commentspagetitle');
 $this->headTitle($title);
 ?>
            <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        <?php echo $this->escapeHtml($title); ?>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
                        <li class="active"><?php echo $this->translate('commentspagetitle');?></li>
                    </ol>
                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <div id="error" style="display: none" class="callout callout-danger">
                                    </div>
                                    
                                    <!--<p>
                                        <a href="<?php echo $this->url('Comment', array('action'=>'add'));?>">Add new Comment</a>
                                    </p>-->
                                </div>
                                <div class="box-body">
                                    <table id="commentDataTable" class="table table-bordered table-hover dataTable" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th><?php echo $this->translate('tableid');?></th>
                                                <!-- <th><?php echo $this->translate('tabletitle');?></th> 
                                                <th><?php echo $this->translate('tablecontent');?></th> -->
                                                <th><?php echo $this->translate('tableuser');?></th>
                                                <th><?php echo $this->translate('tabledate');?></th>
                                                <th>auther</th>
                                                <th><?php echo $this->translate('tablestatus');?></th>
                                                <th><?php echo $this->translate('tableoptions');?></th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    
                </section><!-- /.content -->
 
<?php $this->inlineScript()->captureStart() ?>
                
    $(document).ready(function(){
        function fulldata(){
            $('#commentDataTable').dataTable({
                "destroy": true,
                "lengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]],
                "searching": true,
                "ordering": true,
                "order": [[ 0, "desc" ]],
                "processing": true,
                "ajax" : "<?php echo $this->url('Comment', array('action'=>'getAll'));?>",
                "columnDefs" : [{
                                "targets": 0,
                                "data": "id",
                                "render": function ( data, type, full, meta ) {
                                            return data;
                                        }
                                    },{
                                "targets": 1,
                                "data": "username",
                                "render": function ( data, type, full, meta ) {
                                            return data;
                                        }
                                    },{
                                "targets": 2,
                                "data": "comment_date",
                                "render": function ( data, type, full, meta ) {
                                            return data;
                                        }
                                    },{
                                "targets": 3,
                                "data": "userid",
                                "visible": false,
                                "render": function ( data, type, full, meta ) {
                                            return data;
                                        }
                                    },{
                                "targets": 4,
                                "data": "active",
                                "render": function ( data, type, full, meta ) {
                                            var activeicon='fa fa-close';
                                            var activemsg='Activate';
                                            if(data){
                                                activeicon='fa fa-check';
                                                activemsg='Deactivate';
                                            }
                                            return "<a rel='" + full.id + "' class='btn btn-xs chstatus' data-toggle='tooltip' data-placement='top' title='"+ activemsg +"'><i class='"+ activeicon +"'></i></a>";
                                        }
                                    },{
                                "targets": 5,
                                "data": "id",
                                "render": function ( data, type, full, meta ) {
                                    return "<a rel='"+ data +"' class='btn btn-xs delete' data-toggle='tooltip' data-placement='top' title='Delete'><i class='fa fa-trash'></i></a>\n\
                                    <a href='<?php echo $this->url('Comment', array('action'=>'edit'));?>"+ data +"' class='btn btn-xs' data-toggle='tooltip' data-placement='top' title='Edit'><i class='fa fa-edit'></i></a>";
                                }
                }]
                ,initComplete: function () {
                    var authorColumn = this.api().columns(3);
                    $('#auther').on( 'change', function () {
                        authorColumn
                            .columns( 3 )
                            .search( this.value )
                            .draw();
                    });
                }
            });
        };
        <?php
        $adminUser= $this->zfcUserIdentity()->getIsAdmin();
        if($adminUser){
        ?>
            $.getJSON("<?php echo $this->url('Users', array('action' => 'getAll')) ?>", function(result){
            $("<span>User: </span>").appendTo('.box-header' );
            var select = $("<select id='auther'><option value=''></option></select>").appendTo('.box-header' );
                $.each(result.data, function(index, element) {
                select.append( '<option value="'+element.id+'">'+element.displayName+'</option>' )    
                });
            });
        <?php
        }
        ?>
         
        fulldata();
         
        $('#commentDataTable tbody').on('click', '.delete', function () {
            var data = $(this).attr('rel');
            bootbox.confirm("<?php echo $this->translate('yesorno');?>", function(result) {
                if(result){
                    $.post(
                            "<?php echo $this->url('Comment', array('action'=>'delete'));?>"+data,
                             function (data){
                                 //data = JSON.stringify(data);
                                 if(data.done == 'true'){
                                     fulldata();
                                 }else{
                                 $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                                     $('#error').show(150);
                                 }
                             }
                    );
                }
            }); 
        });
        
        $('#commentDataTable tbody').on('click', '.chstatus', function () {
            var data = $(this).attr('rel');
            $.post(
                    "<?php echo $this->url('Comment', array('action'=>'chstatus'));?>"+data,
                     function (data){
                         if(data.done == 'true'){
                             fulldata();
                         }else{
                         $('#error').html('<h4>Error In Submit!</h4><p>'+data.message+'</p>');
                             $('#error').show(150);
                         }
                     }
            );
        });
     });

     <?php $this->inlineScript()->captureEnd() ?>