<?php
// module/Album/view/album/album/edit.phtml:

$title = $this->translate('edit')." ".$this->translate('sectionpagetitle');
$this->headTitle($title);
?>

<section class="content-header">
    <h1>
        <?php echo $this->escapeHtml($title); ?>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('home') ?>"><i class="fa fa-dashboard"></i><?php echo $this->translate('dashbord');?></a></li>
        <li><a href="<?php echo $this->url('Sections') ?>"><?php echo $this->translate('sectionpagetitle');?></a></li>
        <li class="active"><?php echo $this->escapeHtml($title); ?></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <!-- general form elements disabled -->
            <div class="box box-primary">

                <div class="box-body">

                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('Sections', array('action' => 'edit', 'id' => $this->id,)));
                    $form->setAttribute('data-toggle' , 'validator');
                    $form->setAttribute('role', 'form');
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('id'));
                    ?>
                    <div class="form-group">
                        <label for='enName'><?php echo $this->translate('name');?></label>
                        <?php
                        echo $this->formRow($form->get('name'));
                        ?>
                        <span class="help-block with-errors"> <?php echo $this->translate('englishTitleVal');?> </span>
                    </div>

                    <div class="form-group">
                        <label for='arName'><?php echo $this->translate('tabletype');?></label>
                        <?php
                        echo $this->formRow($form->get('type'));
                        ?>
                        <span class="help-block with-errors"> <?php echo $this->translate('arabicTitleVal');?> </span>
                    </div>

                    <div class="box-footer">
                        <?php
                        echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>